"""PostgreSQL evidence for immutable expense drafts, approvals and receipts."""
import json
from uuid import uuid4

import pytest
from sqlalchemy import text
from sqlalchemy.exc import DBAPIError

from modules.accounting import expenses
from modules.accounting.expense_models import ExpenseArticle
from modules.accounting.expense_schemas import BudgetLine
from tests.accounting.test_expense_control import budget_command, catalog_command
from tests.accounting.test_postgres import pg_factory  # noqa: F401
from tests.integration.test_invoice_issuance_postgres import issuance_pg  # noqa: F401


async def test_pg_expense_draft_replay_history_and_exact_cells(issuance_pg):  # noqa: F811
    api, factory = issuance_pg
    org = await api.post("/accounting/organizations", json={"name": "Synthetic expense book", "unp": "999999934"})
    assert org.status_code == 201, org.text
    prefix = f"/accounting/organizations/{org.json()['id']}"
    headers = {"X-Expected-Principal": "tester"}
    # Fixture identity is obtained from the actual scoped endpoint.
    context = await api.get(prefix + "/expense-catalog")
    assert context.status_code == 200, context.text
    headers["X-Expected-Principal"] = context.json()["principal"]
    catalog = await api.post(prefix + "/expense-catalog/commands", headers=headers,
        json=catalog_command().model_dump(mode="json"))
    assert catalog.status_code == 200, catalog.text
    command = budget_command(catalog.json()["result"]["articles"][0]["id"]).model_dump(mode="json")
    first = await api.post(prefix + "/expense-budgets/drafts", headers=headers, json=command)
    assert first.status_code == 200, first.text
    repeat = await api.post(prefix + "/expense-budgets/drafts", headers=headers, json=command)
    assert repeat.json() == first.json()
    async with factory() as session:
        cells = await session.scalar(text("SELECT months FROM accounting.expense_budget_line"))
        assert cells == ["0.00", "12.50"] + [None] * 10
        with pytest.raises(DBAPIError, match="committed expense budget"):
            async with session.begin_nested():
                await session.execute(text("""INSERT INTO accounting.expense_budget_line
                    (organization_id,budget_id,article_id,months,article_snapshot)
                    SELECT l.organization_id,l.budget_id,a.id,l.months,l.article_snapshot
                    FROM accounting.expense_budget_line l
                    JOIN accounting.expense_article a ON a.organization_id=l.organization_id
                    AND a.id<>l.article_id LIMIT 1"""))
        with pytest.raises(DBAPIError, match="generated by its insert trigger"):
            async with session.begin_nested():
                await session.execute(text("""INSERT INTO accounting.expense_budget_transaction
                    SELECT id,txid_current() FROM accounting.expense_budget LIMIT 1"""))
        for sql in (
            "UPDATE accounting.expense_budget_transaction SET root_transaction=txid_current()",
            "DELETE FROM accounting.expense_budget_transaction",
            "TRUNCATE accounting.expense_budget_transaction",
        ):
            with pytest.raises(DBAPIError, match="immutable"):
                async with session.begin_nested():
                    await session.execute(text(sql))
        for table in ("expense_budget", "expense_budget_line", "expense_command_receipt"):
            for sql in (f"UPDATE accounting.{table} SET id=id", f"DELETE FROM accounting.{table}",
                        f"TRUNCATE accounting.{table} CASCADE"):
                with pytest.raises(DBAPIError, match="immutable"):
                    async with session.begin_nested():
                        await session.execute(text(sql))
        for values in ([None] * 11, [1.25] + [None] * 11, ["-1.00"] + [None] * 11):
            with pytest.raises(DBAPIError, match="monthly cells|decimal string"):
                async with session.begin_nested():
                    await session.execute(text("""INSERT INTO accounting.expense_budget_line
                        (organization_id,budget_id,article_id,months,article_snapshot)
                        SELECT organization_id,budget_id,article_id,CAST(:cells AS json),article_snapshot
                        FROM accounting.expense_budget_line LIMIT 1"""), {"cells": json.dumps(values)})
        # A real savepoint birth must still allow lines in the outer root.
        # Roll back this synthetic package; it is not an authorized API command.
        package = await session.begin_nested()
        async with session.begin_nested():
            new_id = await session.scalar(text("""INSERT INTO accounting.expense_budget
                (organization_id,year,currency,basis,revision,state,catalog_revision,actor,evidence)
                SELECT organization_id,year,currency,basis,revision+1,state,catalog_revision,actor,evidence
                FROM accounting.expense_budget ORDER BY id LIMIT 1 RETURNING id"""))
        await session.execute(text("""INSERT INTO accounting.expense_budget_line
            (organization_id,budget_id,article_id,months,article_snapshot)
            SELECT organization_id,:budget_id,article_id,months,article_snapshot
            FROM accounting.expense_budget_line ORDER BY id LIMIT 1"""), {"budget_id": new_id})
        assert await session.scalar(text("""SELECT count(*) FROM accounting.expense_budget_transaction
            WHERE budget_id=:id AND root_transaction=txid_current()"""), {"id": new_id}) == 1
        with pytest.raises(DBAPIError, match="requires its command receipt"):
            async with session.begin_nested():
                await session.execute(text("SET CONSTRAINTS ALL IMMEDIATE"))
        await package.rollback()
        assert await session.scalar(text("""SELECT count(*) FROM accounting.expense_budget_transaction
            WHERE budget_id=:id"""), {"id": new_id}) == 0


@pytest.mark.parametrize("tamper", [False, True])
async def test_pg_budget_receipt_seals_exact_result(issuance_pg, monkeypatch, tamper):  # noqa: F811
    api, factory = issuance_pg
    response = await api.post("/accounting/organizations", json={
        "name": "Synthetic receipt proof", "unp": "999999935"})
    assert response.status_code == 201, response.text
    org_id = response.json()["id"]
    async with factory() as session:
        catalog = await expenses.execute(session, org_id, "tester", "catalog", catalog_command())
        await session.commit()
        article = catalog["result"]["articles"][0]["id"]
        if tamper:
            original = expenses.budget_payload

            async def wrong_result(session, budget):
                result = await original(session, budget)
                # Application recomputes every digest over this false result.
                result["evidence"] = "Forged but correctly hashed"
                return result

            monkeypatch.setattr(expenses, "budget_payload", wrong_result)
            with pytest.raises(DBAPIError, match="does not match stored budget"):
                async with session.begin_nested():
                    await expenses.execute(session, org_id, "tester", "budget", budget_command(article))
            assert await session.scalar(text("SELECT count(*) FROM accounting.expense_budget")) == 0
            return
        receipt = await expenses.execute(session, org_id, "tester", "budget", budget_command(article))
        await session.execute(text("SET CONSTRAINTS ALL IMMEDIATE"))
        with pytest.raises(DBAPIError, match="sealed by its command receipt"):
            async with session.begin_nested():
                await session.execute(text("""INSERT INTO accounting.expense_budget_line
                    (organization_id,budget_id,article_id,months,article_snapshot)
                    SELECT l.organization_id,l.budget_id,a.id,l.months,l.article_snapshot
                    FROM accounting.expense_budget_line l
                    JOIN accounting.expense_article a ON a.organization_id=l.organization_id
                    AND a.id<>l.article_id LIMIT 1"""))
        await session.commit()
        assert await expenses.execute(session, org_id, "tester", "budget",
            budget_command(article, request_key=receipt["request_key"])) == receipt


async def test_pg_budget_approval_is_immutable_and_requires_receipt(issuance_pg):  # noqa: F811
    api, factory = issuance_pg
    response = await api.post("/accounting/organizations", json={
        "name": "Synthetic approval proof", "unp": "999999937"})
    assert response.status_code == 201, response.text
    org_id = response.json()["id"]
    prefix = f"/accounting/organizations/{org_id}"
    context = await api.get(prefix + "/expense-catalog")
    assert context.status_code == 200, context.text
    headers = {"X-Expected-Principal": context.json()["principal"]}
    catalog = await api.post(prefix + "/expense-catalog/commands", headers=headers,
        json=catalog_command().model_dump(mode="json"))
    assert catalog.status_code == 200, catalog.text
    article = catalog.json()["result"]["articles"][0]["id"]
    draft = await api.post(prefix + "/expense-budgets/drafts", headers=headers,
        json=budget_command(article).model_dump(mode="json"))
    assert draft.status_code == 200, draft.text
    approval = {
        "request_key": str(uuid4()),
        "budget_id": draft.json()["result"]["id"],
        "expected_revision": 1,
        "evidence": "Synthetic chief approval",
    }
    first = await api.post(prefix + "/expense-budgets/approve", headers=headers, json=approval)
    assert first.status_code == 200, first.text
    assert first.json()["kind"] == "budget_approval"
    assert (await api.post(prefix + "/expense-budgets/approve", headers=headers, json=approval)).json() == first.json()
    view = await api.get(prefix + "/expense-budgets?year=2026&currency=BYN&basis=cash")
    assert view.json()["approved_plan"]["budget_id"] == approval["budget_id"]
    second = await api.post(prefix + "/expense-budgets/drafts", headers=headers,
        json=budget_command(article, revision=1).model_dump(mode="json"))
    assert second.status_code == 200, second.text
    second_id = second.json()["result"]["id"]
    async with factory() as session:
        with pytest.raises(DBAPIError, match="immutable"):
            async with session.begin_nested():
                await session.execute(text("UPDATE accounting.expense_budget_approval SET evidence=evidence"))
        forged_key = str(uuid4())
        with pytest.raises(DBAPIError, match="requires its command receipt"):
            async with session.begin_nested():
                await session.execute(text("""INSERT INTO accounting.expense_budget_approval
                    (organization_id,budget_id,budget_revision,actor,evidence,request_key,budget_snapshot,approval_digest)
                    SELECT organization_id,id,revision,'tester','Forged',:request_key,
                           accounting.expense_budget_payload(id),'0000000000000000000000000000000000000000000000000000000000000000'
                    FROM accounting.expense_budget WHERE id=:budget_id"""),
                    {"request_key": forged_key, "budget_id": second_id})
                await session.execute(text("SET CONSTRAINTS ALL IMMEDIATE"))


@pytest.mark.parametrize("line_count", [0, 301])
async def test_pg_budget_line_bounds_bypass_input_validation(issuance_pg, line_count):  # noqa: F811
    api, factory = issuance_pg
    response = await api.post("/accounting/organizations", json={
        "name": "Synthetic line bounds", "unp": "999999936"})
    assert response.status_code == 201, response.text
    org_id = response.json()["id"]
    async with factory() as session:
        catalog = await expenses.execute(session, org_id, "tester", "catalog", catalog_command())
        articles = [ExpenseArticle(organization_id=org_id,
            group_id=catalog["result"]["groups"][0]["id"], code=f"synthetic-{i}", title=f"Test {i}")
            for i in range(line_count)]
        session.add_all(articles)
        await session.flush()
        lines = [BudgetLine(article_id=a.id, months=[None] * 12) for a in articles]
        await session.commit()
        # Bypass the API bound; valid hashes are still generated by the service.
        cmd = budget_command(catalog["result"]["articles"][0]["id"]).model_copy(update={"lines": lines})
        with pytest.raises(DBAPIError, match="between 1 and 300 lines"):
            async with session.begin_nested():
                await expenses.execute(session, org_id, "tester", "budget", cmd)
        for table in ("expense_budget", "expense_budget_transaction", "expense_budget_line"):
            assert await session.scalar(text(f"SELECT count(*) FROM accounting.{table}")) == 0
        assert await session.scalar(text("SELECT count(*) FROM accounting.expense_command_receipt WHERE kind='budget'")) == 0
