"""SQL-only entry birth proof across real PostgreSQL root/subtransactions."""
import pytest
from sqlalchemy import func, select, text
from sqlalchemy.exc import DBAPIError

from core.domain.models import OutboxEvent
from core.services.eventbus import OutboxEventBus
from modules.accounting import service
from modules.accounting.models import Entry, Line
from tests.accounting.test_postgres import pg_book, pg_factory  # noqa: F401


async def test_entry_lines_and_outbox_can_commit_from_a_real_savepoint(pg_factory, pg_book, posting):  # noqa: F811
    async with pg_factory() as session:
        root = await session.scalar(text("SELECT txid_current()"))
        async with session.begin_nested():
            entry = await service.post(session, pg_book[0], posting("nested"), "tester", OutboxEventBus())
            proof = await session.scalar(text("SELECT root_transaction FROM accounting.entry_transaction WHERE entry_id=:id"), {"id": entry.id})
            born = await session.scalar(text("SELECT xmin::text::bigint FROM accounting.entry WHERE id=:id"), {"id": entry.id})
            assert proof == root and born != root % 4294967296
        await session.commit()
        entry_id = entry.id
    async with pg_factory() as session:
        assert await session.scalar(select(func.count()).select_from(Entry)) == 1
        assert await session.scalar(select(func.count()).select_from(Line)) == 2
        assert await session.scalar(select(func.count()).select_from(OutboxEvent)) == 1
        for sql, match in [
            ("UPDATE accounting.entry_transaction SET root_transaction=txid_current()", "immutable"),
            ("DELETE FROM accounting.entry_transaction", "immutable"),
            ("TRUNCATE accounting.entry_transaction", "immutable"),
            # Additive accounting registers may reference a line; cascade only
            # to reach the line immutability trigger under the synthetic schema.
            ("TRUNCATE accounting.line CASCADE", "immutable"),
            ("TRUNCATE accounting.entry CASCADE", "immutable"),
            (f"INSERT INTO accounting.entry_transaction VALUES ({entry_id},txid_current())", "generated by its insert trigger"),
        ]:
            with pytest.raises(DBAPIError, match=match):
                async with session.begin_nested():
                    await session.execute(text(sql))
        with pytest.raises(DBAPIError, match="committed entry"):
            async with session.begin_nested():
                await session.execute(text("""INSERT INTO accounting.line
                    (entry_id,account_id,account_code,account_title,category,cash,side,amount,dimensions,currency)
                    SELECT entry_id,account_id,account_code,account_title,category,cash,side,amount,dimensions,currency
                    FROM accounting.line WHERE entry_id=:id LIMIT 1"""), {"id": entry_id})


async def test_rolled_back_savepoint_leaves_no_entry_proof_or_outbox(pg_factory, pg_book, posting):  # noqa: F811
    async with pg_factory() as session:
        with pytest.raises(ValueError, match="Synthetic rollback"):
            async with session.begin_nested():
                await service.post(session, pg_book[0], posting("rolled-back"), "tester", OutboxEventBus())
                assert await session.scalar(text("SELECT count(*) FROM accounting.entry_transaction")) == 1
                raise ValueError("Synthetic rollback")
        await session.commit()
    async with pg_factory() as session:
        for model in (Entry, Line, OutboxEvent):
            assert await session.scalar(select(func.count()).select_from(model)) == 0
        assert await session.scalar(text("SELECT count(*) FROM accounting.entry_transaction")) == 0
