"""Shared bounded attachment decoding and durable local writes (no remote fetching)."""
from __future__ import annotations

import base64
import binascii
import hashlib
import os
import re
import tempfile
from pathlib import Path

ALLOWED_CONTENT_TYPES = {
    "application/pdf": ".pdf",
    "application/msword": ".doc",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": ".xlsx",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": ".docx",
    "image/jpeg": ".jpg",
    "image/png": ".png",
}
MAX_SIZE_BYTES = 10 * 1024 * 1024
MAX_B64_CHARS = (MAX_SIZE_BYTES // 3 + 1) * 4


class AttachmentRejected(ValueError):
    """Invalid attachment or a file outside the configured storage root."""


def attachment_root() -> Path:
    return Path(os.getenv("AIOS_LEADS_DATA_DIR", "./data/leads/attachments"))


def decode_data_url(data_url: str, max_b64_chars: int = MAX_B64_CHARS) -> tuple[str, bytes]:
    match = re.fullmatch(r"data:([^;]+);base64,(.+)", data_url, re.DOTALL)
    if not match:
        raise AttachmentRejected("Ожидался data-URI вида data:<mime>;base64,<...>")
    content_type, encoded = match.groups()
    if len(encoded) > max_b64_chars:
        raise AttachmentRejected("Файл превышает допустимый размер")
    try:
        return content_type, base64.b64decode(encoded, validate=True)
    except (binascii.Error, ValueError) as exc:
        raise AttachmentRejected("Некорректный base64") from exc


def validate_attachment(content_type: str, data: bytes, max_size: int = MAX_SIZE_BYTES) -> None:
    if content_type not in ALLOWED_CONTENT_TYPES:
        raise AttachmentRejected("Тип файла не поддерживается")
    if not data or len(data) > max_size:
        raise AttachmentRejected("Недопустимый размер файла")


def resolve_path(root: Path, storage_path: str) -> Path:
    path = (root / storage_path).resolve()
    if root.resolve() not in path.parents:
        raise AttachmentRejected("Некорректный путь вложения")
    return path


def _sync_directory(path: Path) -> None:
    # Linux production: persist both rename and directory creation. Windows does
    # not provide directory fsync; Windows tests prove process-restart semantics only.
    if os.name != "nt":
        descriptor = os.open(path, os.O_RDONLY | os.O_DIRECTORY)
        try:
            os.fsync(descriptor)
        finally:
            os.close(descriptor)


def durable_write(root: Path, storage_path: str, data: bytes) -> None:
    """Atomic file + fsync before DB acknowledgement; paths are generated by the server."""
    destination = resolve_path(root, storage_path)
    missing = []
    parent = destination.parent
    while not parent.exists():
        missing.append(parent)
        parent = parent.parent
    for directory in reversed(missing):
        directory.mkdir(exist_ok=True)
        _sync_directory(directory.parent)
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(dir=destination.parent, prefix=".intake-", delete=False) as f:
            temporary = Path(f.name)
            f.write(data)
            f.flush()
            os.fsync(f.fileno())
        os.replace(temporary, destination)
        # Also flush ancestor entries left behind by an earlier interrupted mkdir.
        # A retry must not treat an existing, but not yet durable, directory as safe.
        directory = destination.parent
        while True:
            _sync_directory(directory)
            if directory.parent == directory:
                break
            directory = directory.parent
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def verify_file(root: Path, item: dict) -> None:
    """Verify bytes, not only the existence of a DB attachment row."""
    path = resolve_path(root, item["storage_path"])
    if path.stat().st_size != item["size_bytes"]:
        raise AttachmentRejected("Размер сохранённого файла не совпадает")
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            digest.update(chunk)
    if digest.hexdigest() != item["sha256"]:
        raise AttachmentRejected("Хеш сохранённого файла не совпадает")
