from copy import deepcopy

import pytest
from sqlalchemy import func, select

from core.domain.models import OutboxEvent
from modules.sales import documents
from modules.sales.invoice_issuance import canonical_request
from modules.sales.models import DealDocument
from modules.sales.schemas import InvoiceCreate
from modules.wms.invoice_reservations import InvoiceReservation
from modules.wms.models import StockMovement
from tests.test_invoice_issuance import command, create, seed


async def on_order_flow(api, session):
    ids, base = await seed(api, session, physical="0")
    base["reserve_mode"] = "on_order"
    preview = await api.post(f"/sales/deals/{ids['deal']}/invoice-preview", json=base)
    assert preview.status_code == 200, preview.text
    p = preview.json()
    assert p["reserve_mode"] == "on_order" and p["availability"] is None
    body = {**base, "request_key": "on-order-original", "expected_document_version": p["document_version"],
            "expected_basis_digest": p["basis_digest"], "allocations": [], "unreserved_confirmed": True}
    refused = await create(api, ids, {**body, "unreserved_confirmed": False})
    assert refused.status_code == 422
    before = await session.scalar(select(func.count()).select_from(StockMovement))
    issued = await create(api, ids, body)
    assert issued.status_code == 201, issued.text
    result = issued.json()
    assert result["document"]["reserve_mode"] == "on_order"
    assert result["document"]["reserve_status"] == "unreserved"
    assert result["reservation_digest"] is None
    doc = await session.get(DealDocument, result["document"]["id"])
    assert doc.reserved_at is None and "Под заказ — товар не зарезервирован" in doc.original_html
    assert await session.scalar(select(func.count()).select_from(InvoiceReservation)) == 0
    assert await session.scalar(select(func.count()).select_from(StockMovement)) == before
    events = (await session.scalars(select(OutboxEvent.event_type))).all()
    assert "sales.invoice.issued" in events and "sales.stock.reserved" not in events
    replay = await create(api, ids, body)
    assert replay.status_code == 200 and replay.json()["replayed"]
    changed = {**body, "reserve_mode": "stock", "unreserved_confirmed": False,
               "journal_complete": True, "evidence": "Explicit stock", "allocations": [{"line_no": 1, "warehouse": "W", "qty": "2.00"}]}
    assert (await create(api, ids, changed)).status_code == 409
    from modules.sales.reservation_source import SalesReservationSource
    with pytest.raises(ValueError):
        await SalesReservationSource().invoice_shipping_source(session, result["document"]["id"], organization_id=ids["org"],
            expected_version=result["document_version"], expected_content_sha256=result["content_sha256"])


async def test_on_order_no_stock_and_exact_retry(api, session):
    await on_order_flow(api, session)


async def test_on_order_expiry_reminds_once_without_creating_stock_reserve(api, session, monkeypatch):
    from datetime import datetime, time, timedelta, timezone

    from modules.sales.reserve import tick_invoice_reserve

    await on_order_flow(api, session)
    doc = await session.scalar(select(DealDocument).where(DealDocument.status == "issued"))
    original = doc.original_html
    moment = datetime.combine(doc.valid_until - timedelta(days=1), time(12), timezone.utc)
    monkeypatch.setattr("modules.sales.reserve._utcnow", lambda: moment)
    services = api._transport.app.state.core.services
    for _ in range(2):
        await tick_invoice_reserve(session, services)
        await session.commit()
    reminders = (await session.scalars(select(OutboxEvent).where(
        OutboxEvent.event_type == "sales.invoice.expiring"))).all()
    assert len(reminders) == 1
    assert reminders[0].payload["document_id"] == doc.id
    assert reminders[0].payload["customer_notification"] == "requires_authorized_send"
    await session.refresh(doc)
    assert (doc.status, doc.reserve_status, doc.original_html) == ("issued", "unreserved", original)
    assert await session.scalar(select(func.count()).select_from(InvoiceReservation)) == 0


async def test_stock_request_hash_remains_historical(api, session):
    ids, base = await seed(api, session)
    body, _ = await command(api, ids, base)
    # Old format explicitly constructed, never generated by the new canonicalizer.
    historical = deepcopy(body)
    historical.update(operation="erp_invoice_issue", deal_id=ids["deal"], document_id=None)
    historical["pricing"] = sorted(historical["pricing"], key=lambda row: row["item_id"])
    historical["allocations"] = sorted(historical["allocations"], key=lambda row: (row["line_no"], row["warehouse"]))
    data = InvoiceCreate.model_validate({"kind": "invoice", **body})
    assert documents.digest(canonical_request(ids["deal"], None, data)) == documents.digest(historical)
