"""sales: durable outgoing email and delivery attempts.

Number selected by CRM-SEND-001 after operator delegated selection on 2026-09-09.
Reparent this unreleased migration after the immutable-documents migration when
that dependency is integrated. Do not deploy with multiple Alembic heads.
Downgrade deletes queued messages and audit attempts: export them first.
"""

import sqlalchemy as sa
from alembic import op

revision = "0116"
down_revision = "0114"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outgoing_email",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("deal_id", sa.Integer(), nullable=False),
        sa.Column("request_key", sa.String(length=64), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("confirmed_by", sa.String(length=128), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("sender", sa.String(length=254), nullable=False),
        sa.Column("to", sa.JSON(), nullable=False),
        sa.Column("cc", sa.JSON(), nullable=False),
        sa.Column("subject", sa.String(length=250), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("attachments", sa.JSON(), nullable=False),
        sa.Column("mime", sa.LargeBinary(), nullable=False),
        sa.Column("mime_sha256", sa.String(length=64), nullable=False),
        sa.Column("message_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("round_attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(), nullable=True),
        sa.Column("claim_token", sa.String(length=36), nullable=True),
        sa.Column("claimed_at", sa.DateTime(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column("last_reason", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["deal_id"], ["sales.deal.id"], name=op.f("fk_outgoing_email_deal_id_deal")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outgoing_email")),
        sa.UniqueConstraint("created_by", "request_key", name="uq_outgoing_email_request"),
        sa.UniqueConstraint("message_id", name=op.f("uq_outgoing_email_message_id")),
        schema="sales",
    )
    op.create_index(
        "ix_outgoing_email_due",
        "outgoing_email",
        ["status", "next_attempt_at"],
        unique=False,
        schema="sales",
    )
    op.create_index(
        op.f("ix_sales_outgoing_email_deal_id"),
        "outgoing_email",
        ["deal_id"],
        unique=False,
        schema="sales",
    )
    op.create_table(
        "email_attempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_id", sa.String(length=36), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=True),
        sa.Column("smtp_code", sa.Integer(), nullable=True),
        sa.Column("recipients", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["sales.outgoing_email.id"],
            name=op.f("fk_email_attempt_email_id_outgoing_email"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_attempt")),
        sa.UniqueConstraint("email_id", "number", name="uq_email_attempt_number"),
        schema="sales",
    )
    op.create_index(
        op.f("ix_sales_email_attempt_email_id"),
        "email_attempt",
        ["email_id"],
        unique=False,
        schema="sales",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("email_attempt", schema="sales")
    op.drop_table("outgoing_email", schema="sales")
