"use client";
import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cancelAttempt,currentMoney,currentReview,definiteRejection,fetchBasis,forgetReview,moneyAttempt,object,persist,readJournal,reviewAttempt,sections,sendAttempt,settle,
 type Attempt,type Basis,type CancelReceipt,type ExternalSource,type Journal,type Scope } from "@/lib/invoice-cancellation-api";
const titles={wms_issue:"Физическое выбытие со склада",wms_pick:"Подбор товара",logistics_shipment:"Перевозка и неисполненные планы",accounting_issue:"Бухгалтерские основания",legacy_fulfillment:"Внешняя история исполнения"};
const reasons:Record<string,string>={money_not_fully_refunded_or_unknown:"Оплата возвращена не полностью либо история неизвестна",funds_not_fully_refunded:"Остались невозвращённые средства",physical_shipment_requires_return_workflow:"Есть физическая отгрузка: нужен отдельный процесс возврата",legacy_paid_without_receipts:"Историческая отметка оплаты не подтверждена поступлениями",known_bank_unallocated:"Банковская операция ещё не распределена"};
const msg=(e:unknown)=>e instanceof Error?e.message:"Не удалось проверить основания.";
function detailText(v:unknown):string{if(typeof v==="string")return v;if(Array.isArray(v))return v.map(detailText).filter(Boolean).join(", ");if(object(v))return Object.entries(v).map(([k,x])=>`${k}: ${detailText(x)}`).join("; ");return v===null?"":String(v);}
function summary(name:typeof sections[number],facts:Record<string,unknown>){if(name==="wms_issue")return facts.observed_state==="no_shipment"?"В проверенных данных WMS выбытие не обнаружено. Внешняя история проверяется отдельно.":"Есть выбытие или неопределённая история; отмена требует отдельной проверки.";if(name==="wms_pick")return `Связанных заданий: ${Array.isArray(facts.picks)?facts.picks.length:"неизвестно"}. Неисполненный подбор может быть закрыт вместе со снятием резерва.`;if(name==="logistics_shipment")return `Планов: ${Array.isArray(facts.shipments)?facts.shipments.length:"неизвестно"}; тендеров: ${Array.isArray(facts.rfqs)?facts.rfqs.length:"неизвестно"}. Заказ перевозчику и исполнение требуют реального останова.`;if(name==="accounting_issue"){const ledger=object(facts.facts)?facts.facts:{};return `Проводок: ${Array.isArray(ledger.entries)?ledger.entries.length:"неизвестно"}. Неразобранные ручные записи и очереди требуют сверки.`;}return `Необходимо проверить все именованные источники за период ${String(facts.required_history_from)} — ${String(facts.required_history_through)}.`;}
export function InvoiceCancellation({scope,onCancelled}:{scope:Scope;onCancelled:()=>void}){return <Panel key={`${scope.org}:${scope.deal}:${scope.document}`} scope={scope} onCancelled={onCancelled}/>;}
function Panel({scope,onCancelled}:{scope:Scope;onCancelled:()=>void}){
 const [basis,setBasis]=useState<Basis|null>(null),[journal,setJournal]=useState<Journal|null>(null),[error,setError]=useState(""),[storageError,setStorageError]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[rejected,setRejected]=useState<{attempt:Attempt;reason:string}|null>(null),[success,setSuccess]=useState<CancelReceipt|null>(null);
 const [moneyEvidence,setMoneyEvidence]=useState(""),[moneyReferences,setMoneyReferences]=useState(""),[from,setFrom]=useState(""),[through,setThrough]=useState(""),[moneyChecked,setMoneyChecked]=useState(false);
 const [sources,setSources]=useState<ExternalSource[]>([]),[reviewEvidence,setReviewEvidence]=useState(""),[reviewChecked,setReviewChecked]=useState(false),[cancelEvidence,setCancelEvidence]=useState(""),[invalidated,setInvalidated]=useState(false);
 const live=useRef(false),generation=useRef(0),lock=useRef(false);
 useEffect(()=>{live.current=true;const token=++generation.current;void Promise.resolve().then(async()=>{try{const j=readJournal(scope);if(!live.current||generation.current!==token)return;setJournal(j);const b=await fetchBasis(scope);if(live.current&&generation.current===token){setBasis(b);setFrom(b.money.required_history_from);setThrough(b.money.required_history_through);}}catch(e){if(live.current&&generation.current===token){setError(msg(e));try{readJournal(scope);}catch{setStorageError(true);}}}finally{if(live.current&&generation.current===token)setLoading(false);}});return()=>{live.current=false;};
 // Each mounted panel owns one exact scope and its own callback generation.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[]);
 async function refresh(){if(lock.current)return;lock.current=true;const token=++generation.current;setBusy(true);setError("");try{const b=await fetchBasis(scope);if(live.current&&token===generation.current){setBasis(b);setJournal(readJournal(scope));setFrom(b.money.required_history_from);setThrough(b.money.required_history_through);setMoneyChecked(false);setReviewChecked(false);setInvalidated(false);}}catch(e){if(live.current&&token===generation.current)setError(msg(e));}finally{lock.current=false;if(live.current&&token===generation.current)setBusy(false);}}
 async function execute(make:()=>Promise<Attempt>|Attempt){if(lock.current||storageError)return;lock.current=true;const token=++generation.current;setBusy(true);setError("");setRejected(null);let attempt:Attempt|undefined;try{attempt=await make();if(!live.current||token!==generation.current)return;persist(attempt);setJournal(readJournal(scope));const receipt=await sendAttempt(attempt);if(!live.current||token!==generation.current)return;if(!settle(attempt,receipt))throw new Error("Журнал уже изменён другой попыткой. Обновите состояние.");setJournal(readJournal(scope));if(attempt.phase==="cancel"){setSuccess(receipt as CancelReceipt);onCancelled();}else{setBasis(null);try{const fresh=await fetchBasis(scope);if(live.current&&token===generation.current){setBasis(fresh);setFrom(fresh.money.required_history_from);setThrough(fresh.money.required_history_through);}}catch(e){if(live.current&&token===generation.current)setError(`Сверка сохранена; актуальность не подтверждена. ${msg(e)}`);}}}catch(e){if(live.current&&token===generation.current){setError(msg(e));if(attempt&&definiteRejection(e))setRejected({attempt,reason:msg(e)});}}finally{lock.current=false;if(live.current&&token===generation.current)setBusy(false);}}
 async function restart(){if(lock.current)return;try{const j=readJournal(scope);if(j.pending){if(!rejected)return;if(!settle(rejected.attempt,undefined,rejected.reason))throw new Error("Попытка изменилась; повторите чтение.");}forgetReview(scope);setJournal(readJournal(scope));setRejected(null);setInvalidated(false);setReviewChecked(false);await refresh();}catch(e){setError(msg(e));}}
 const pending=journal?.pending,record=basis?currentMoney(basis):undefined,review=journal?.review;
 const canReview=!!basis&&!!record&&!basis.preview.observed_blockers.length;
 function reviewSave(){if(!basis)return;void execute(()=>reviewAttempt(scope,basis,reviewEvidence,sources,reviewChecked));}
 function moneySave(){if(!basis)return;void execute(()=>moneyAttempt(scope,basis,{history_from:from,history_through:through,evidence:moneyEvidence.trim(),source_references:moneyReferences.split(/\r?\n/).map(s=>s.trim()).filter(Boolean),all_money_sources_checked:moneyChecked}));}
 function cancelSave(){if(!review)return;void execute(async()=>{const fresh=await fetchBasis(scope);if(live.current)setBasis(fresh);return cancelAttempt(scope,fresh,review,cancelEvidence,invalidated);});}
 return <section aria-label="Аннулирование счёта" className="space-y-4 rounded-xl border border-line bg-surface p-4"><header><h2 className="font-semibold">Аннулирование счёта ID {scope.document}</h2><p className="text-sm text-muted">Юрлицо ID {scope.org}. Действие доступно главному бухгалтеру с актуальным доступом к сделке и источникам.</p></header>
 {loading&&<p role="status">Проверка счёта, денежных оснований и исполнения…</p>}{error&&<p role="alert">{error}</p>}
 {storageError&&<p role="alert">Журнал восстановления недоступен. Новая отправка запрещена.</p>}
 {success?<div role="status"><h3 className="font-semibold">Счёт аннулирован. Резерв снят.</h3><p>Уведомление клиенту не отправлено.</p><p>Основание: {success.actor} · {success.created_at}</p></div>:<>
 {pending&&<div className="space-y-2 rounded-lg border border-amber-400 p-3"><p>Сохранён запрос: {pending.phase==="money"?"денежная сверка":pending.phase==="review"?"сверка исполнения":"аннулирование"}. До проверки результата нельзя создавать новый ключ.</p><Button disabled={busy||storageError} onClick={()=>void execute(()=>pending)}>Повторить сохранённый запрос</Button>{rejected&&<Button variant="secondary" disabled={busy} onClick={()=>void restart()}>Начать новую сверку</Button>}</div>}
 {!pending&&!storageError&&<Button variant="secondary" disabled={busy||loading} onClick={()=>void refresh()}>Обновить основания отмены</Button>}
 {basis&&<><div className="space-y-2"><h3 className="font-semibold">Денежная история</h3><p>Поступило: {basis.preview.money.received}; возвращено: {basis.preview.money.refunded}.</p>{basis.preview.observed_blockers.map(x=><p role="alert" key={x}>{reasons[x]??`Требуется проверка основания: ${x}`}</p>)}<p>{record?"Сохранённая денежная сверка актуальна по проверке сервера.":"Актуальная полная денежная сверка не найдена."}</p></div>
 {!record&&!pending&&!storageError&&<fieldset disabled={busy||!basis.money.can_confirm_money_history} className="space-y-2 rounded border border-line p-3"><legend>Подтвердить денежную историю</legend><label className="block">Начало денежной истории<Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="block">Конец денежной истории<Input type="date" max={basis.money.review_date} value={through} onChange={e=>setThrough(e.target.value)}/></label><label className="block">Денежные источники и ссылки, по одному на строку<textarea className="w-full rounded border border-line p-2" value={moneyReferences} onChange={e=>setMoneyReferences(e.target.value)}/></label><label className="block">Основание денежной сверки<Input value={moneyEvidence} onChange={e=>setMoneyEvidence(e.target.value)}/></label><label className="block"><input type="checkbox" checked={moneyChecked} onChange={e=>setMoneyChecked(e.target.checked)}/> Проверены банк, касса и полная историческая оплата</label><Button onClick={moneySave}>Сохранить денежную сверку</Button></fieldset>}
 <div className="grid gap-3 md:grid-cols-2">{sections.map(name=><article key={name} className="rounded border border-line p-3"><h3 className="font-semibold">{titles[name]}</h3><p className="text-sm">{summary(name,basis.preview.sections[name].facts)}</p>{basis.preview.eligibility_issues?.filter(i=>i.scope===name).map(i=><p role="alert" key={i.code}>{i.message} {detailText(i.detail)}</p>)}</article>)}</div>
 <p className="text-sm text-muted">Дополнительные ограничения проверит сервер при сохранении. Заказ перевозчику, физическая отгрузка и неразобранные ручные проводки требуют отдельного подтверждённого процесса.</p>
 {!pending&&!storageError&&(!review||!currentReview(basis,review))&&<fieldset disabled={busy||!canReview} className="space-y-3 rounded border border-line p-3"><legend>Сверка исполнения и внешних источников</legend>{review&&<p role="alert">Сохранённая сверка исполнения не подтверждена как актуальная. Нужна новая проверка.</p>}{sources.map((s,i)=><div key={i} className="space-y-2 border-b border-line pb-3">{(["system","reference","history_from","history_through"] as const).map((field)=><label className="block" key={field}>{({system:"Система или источник",reference:"Документ или ссылка",history_from:"Проверено с",history_through:"Проверено по"})[field]} {i+1}<Input type={field.startsWith("history")?"date":"text"} value={s[field]} onChange={e=>setSources(v=>v.map((row,n)=>n===i?{...row,[field]:e.target.value}:row))}/></label>)}<label><input type="checkbox" checked={s.confirmed_no_fulfillment} onChange={e=>setSources(v=>v.map((row,n)=>n===i?{...row,confirmed_no_fulfillment:e.target.checked}:row))}/> Источник {i+1}: отсутствие исполнения подтверждено</label><Button variant="ghost" onClick={()=>setSources(v=>v.filter((_,n)=>n!==i))}>Удалить источник {i+1}</Button></div>)}<Button variant="secondary" onClick={()=>setSources(v=>[...v,{system:"",reference:"",history_from:String(basis.preview.sections.legacy_fulfillment.facts.required_history_from),history_through:String(basis.preview.sections.legacy_fulfillment.facts.required_history_through),confirmed_no_fulfillment:false}])}>Добавить внешний источник</Button><label className="block">Основание сверки исполнения<textarea className="w-full rounded border border-line p-2" value={reviewEvidence} onChange={e=>setReviewEvidence(e.target.value)}/></label><label className="block"><input type="checkbox" checked={reviewChecked} onChange={e=>setReviewChecked(e.target.checked)}/> Все источники исполнения выявлены и проверены</label><Button onClick={reviewSave}>Сохранить сверку исполнения</Button></fieldset>}
 {!pending&&!storageError&&review&&currentReview(basis,review)&&<fieldset disabled={busy} className="space-y-3 rounded border border-red-400 p-3"><legend>Подтвердить аннулирование</legend><p>Счёт утратит силу. Неисполненные планы будут отозваны, резерв снят. Документы и история сохранятся.</p><label className="block">Причина аннулирования<Input value={cancelEvidence} onChange={e=>setCancelEvidence(e.target.value)}/></label><label className="block"><input type="checkbox" checked={invalidated} onChange={e=>setInvalidated(e.target.checked)}/> Подтверждаю, что счёт больше не будет действителен</label><Button onClick={cancelSave}>Аннулировать счёт</Button></fieldset>}
 </>}
 </>}</section>;
}
