import {webcrypto} from "node:crypto";
import {act,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {afterEach,beforeEach,expect,it,vi} from "vitest";
import {InvoiceCancellation} from "./invoice-cancellation";
import * as api from "@/lib/invoice-cancellation-api";
vi.mock("@/lib/invoice-cancellation-api",async()=>({...await vi.importActual("@/lib/invoice-cancellation-api"),fetchBasis:vi.fn(),sendAttempt:vi.fn()}));
const h="a".repeat(64),key="11111111-1111-4111-8111-111111111111",scope={org:7,deal:3,document:11};
function basis():api.Basis{return{preview:{exact_invoice:{organization_id:7,document_id:11,expected_version:2,expected_content_sha256:h},basis_digest:h,money:{digest:h,state:"no_receipts",received:"0.00",refunded:"0.00"},sections:Object.fromEntries(api.sections.map(n=>[n,{facts:n==="legacy_fulfillment"?{required_history_from:"2026-01-01",required_history_through:"2026-09-10"}:n==="wms_issue"?{observed_state:"no_shipment"}:{picks:[],entries:[],shipments:[],rfqs:[]},sha256:h}])) as api.Preview["sections"],observed_blockers:[],eligibility_issues:[],cancellation_authorized:false},money:{organization_id:7,document_id:11,review_date:"2026-09-10",basis_digest:h,money_state:"no_receipts",blockers:[],required_history_from:"2026-01-01",required_history_through:"2026-09-10",can_confirm_money_history:true,fulfillment_required:true,records:[{id:4,current:true,organization_id:7,document_id:11,basis_digest:h,history_from:"2026-01-01",history_through:"2026-09-10",actor:"chief",created_at:"2026-09-10T00:00:00Z",evidence:"checked",source_references:["bank"]}]}};}
const review:api.ReviewReceipt={review_id:key,review_digest:h,organization_id:7,document_id:11,document_version:2,content_sha256:h,request_key:key,request_hash:h,basis_digest:h,money_reconciliation_id:4,actor:"chief",created_at:"2026-09-10T00:00:00Z",cancellation_authorized:false};
const receipt:api.CancelReceipt={cancellation_id:key,digest:h,organization_id:7,document_id:11,document_version:2,content_sha256:h,request_key:key,request_hash:h,fulfillment_review_id:key,release_id:3,status:"cancelled",reserve_status:"released",customer_notification:"not_sent",actor:"chief",created_at:"2026-09-10T00:00:00Z"};
const makeReview=()=>api.reviewAttempt(scope,basis(),"checked",[{system:"bank",reference:"doc",history_from:"2026-01-01",history_through:"2026-09-10",confirmed_no_fulfillment:true}],true);
function savedReview(){const a=makeReview();api.persist(a);api.settle(a,review);}
beforeEach(()=>{vi.resetAllMocks();vi.stubGlobal("crypto",webcrypto);sessionStorage.clear();vi.mocked(api.fetchBasis).mockResolvedValue(basis());});afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals();});
it("shows five sections and server eligibility reasons without assuming authorization",async()=>{const b=basis();b.preview.observed_blockers=["unexecuted_logistics_withdrawal_required"];b.preview.eligibility_issues=[{scope:"logistics_shipment",code:"stop",message:"Нужен останов перевозчика",detail:"Carrier order 9"}];vi.mocked(api.fetchBasis).mockResolvedValue(b);render(<InvoiceCancellation scope={scope} onCancelled={()=>{}}/>);expect(await screen.findByText(/Нужен останов перевозчика/)).toBeInTheDocument();expect(screen.getByText("Бухгалтерские основания")).toBeInTheDocument();expect(screen.getByRole("button",{name:"Сохранить сверку исполнения"})).toBeDisabled();expect(api.sendAttempt).not.toHaveBeenCalled();});
it("money phase saves a generated UUID before POST",async()=>{const b=basis();b.money.records=[];vi.mocked(api.fetchBasis).mockResolvedValue(b);vi.mocked(api.sendAttempt).mockImplementation(async a=>{expect(api.readJournal(scope).pending).toEqual(a);throw new Error("Ответ потерян");});render(<InvoiceCancellation scope={scope} onCancelled={()=>{}}/>);await screen.findByText("Подтвердить денежную историю");fireEvent.change(screen.getByLabelText("Денежные источники и ссылки, по одному на строку"),{target:{value:"bank:1"}});fireEvent.change(screen.getByLabelText("Основание денежной сверки"),{target:{value:"checked"}});fireEvent.click(screen.getByLabelText("Проверены банк, касса и полная историческая оплата"));fireEvent.click(screen.getByRole("button",{name:"Сохранить денежную сверку"}));await screen.findByText("Ответ потерян");expect(api.readJournal(scope).pending?.phase).toBe("money");});
it.each(["money","review","cancel"] as const)("reload repeats exact %s body even if fresh preview fails",async phase=>{const a:api.Attempt=phase==="money"?api.moneyAttempt(scope,basis(),{history_from:"2026-01-01",history_through:"2026-09-10",evidence:"x",source_references:["bank"],all_money_sources_checked:true}):phase==="review"?makeReview():api.cancelAttempt(scope,basis(),review,"x",true);api.persist(a);vi.mocked(api.fetchBasis).mockRejectedValue(new Error("Terminal preview"));vi.mocked(api.sendAttempt).mockRejectedValue(new api.CancellationError("403",403));render(<InvoiceCancellation scope={scope} onCancelled={()=>{}}/>);fireEvent.click(await screen.findByRole("button",{name:"Повторить сохранённый запрос"}));await screen.findByText("403");expect(api.sendAttempt).toHaveBeenCalledWith(a);expect(api.readJournal(scope).pending).toEqual(a);});
it("fresh CANCEL checks bases again and emits success callback with no notification",async()=>{savedReview();const callback=vi.fn();vi.mocked(api.sendAttempt).mockResolvedValue(receipt);render(<InvoiceCancellation scope={scope} onCancelled={callback}/>);await screen.findByText("Подтвердить аннулирование");fireEvent.change(screen.getByLabelText("Причина аннулирования"),{target:{value:"wrong invoice"}});fireEvent.click(screen.getByLabelText("Подтверждаю, что счёт больше не будет действителен"));fireEvent.click(screen.getByRole("button",{name:"Аннулировать счёт"}));await screen.findByText("Уведомление клиенту не отправлено.");expect(api.fetchBasis).toHaveBeenCalledTimes(2);expect(callback).toHaveBeenCalledOnce();expect(api.readJournal(scope).pending).toBeNull();});
it("stale basis immediately before cancel prevents POST",async()=>{savedReview();vi.mocked(api.fetchBasis).mockResolvedValueOnce(basis()).mockResolvedValue({...basis(),preview:{...basis().preview,basis_digest:"b".repeat(64)}});render(<InvoiceCancellation scope={scope} onCancelled={()=>{}}/>);await screen.findByText("Подтвердить аннулирование");fireEvent.change(screen.getByLabelText("Причина аннулирования"),{target:{value:"wrong"}});fireEvent.click(screen.getByLabelText("Подтверждаю, что счёт больше не будет действителен"));fireEvent.click(screen.getByRole("button",{name:"Аннулировать счёт"}));await screen.findByText(/Сверка исполнения устарела/);expect(api.sendAttempt).not.toHaveBeenCalled();});
it("A to B to A old callback cannot clear a newer pending A",async()=>{const old=makeReview();api.persist(old);let resolve!:(r:api.Receipt)=>void;vi.mocked(api.sendAttempt).mockImplementation(()=>new Promise(r=>{resolve=r;}));const view=render(<InvoiceCancellation scope={scope} onCancelled={()=>{}}/>);fireEvent.click(await screen.findByRole("button",{name:"Повторить сохранённый запрос"}));await waitFor(()=>expect(api.sendAttempt).toHaveBeenCalledOnce());view.rerender(<InvoiceCancellation scope={{...scope,document:12}} onCancelled={()=>{}}/>);api.settle(old,undefined,"verified rejected elsewhere");const newer=makeReview();api.persist(newer);view.rerender(<InvoiceCancellation scope={scope} onCancelled={()=>{}}/>);await screen.findByRole("button",{name:"Повторить сохранённый запрос"});await act(async()=>resolve(review));expect(api.readJournal(scope).pending).toEqual(newer);});
it("definite refusal offers explicit restart and preserves rejected history",async()=>{const a=makeReview();api.persist(a);vi.mocked(api.sendAttempt).mockRejectedValue(new api.CancellationError("stale",409,"Current invoice facts do not support a no-shipment review"));render(<InvoiceCancellation scope={scope} onCancelled={()=>{}}/>);fireEvent.click(await screen.findByRole("button",{name:"Повторить сохранённый запрос"}));const restart=await screen.findByRole("button",{name:"Начать новую сверку"});expect(api.readJournal(scope).pending).toEqual(a);fireEvent.click(restart);await waitFor(()=>expect(api.readJournal(scope).pending).toBeNull());expect(api.readJournal(scope).history[0].outcome).toBe("rejected");});
it("storage quota prevents mutation",async()=>{savedReview();render(<InvoiceCancellation scope={scope} onCancelled={()=>{}}/>);await screen.findByText("Подтвердить аннулирование");const saved=sessionStorage;vi.stubGlobal("sessionStorage",{getItem:saved.getItem.bind(saved),setItem:()=>{throw new Error("quota");}});fireEvent.change(screen.getByLabelText("Причина аннулирования"),{target:{value:"x"}});fireEvent.click(screen.getByLabelText("Подтверждаю, что счёт больше не будет действителен"));fireEvent.click(screen.getByRole("button",{name:"Аннулировать счёт"}));await screen.findByText("quota");expect(api.sendAttempt).not.toHaveBeenCalled();});

it("cancel rejected after fresh preflight allows explicit review restart without losing history", async () => {
  savedReview();
  vi.mocked(api.sendAttempt).mockRejectedValue(new api.CancellationError(
    "Сверка изменилась", 409, "A current confirmed fulfillment review is required",
  ));
  render(<InvoiceCancellation scope={scope} onCancelled={() => {}} />);
  await screen.findByText("Подтвердить аннулирование");
  fireEvent.change(screen.getByLabelText("Причина аннулирования"), {target: {value: "wrong invoice"}});
  fireEvent.click(screen.getByLabelText("Подтверждаю, что счёт больше не будет действителен"));
  fireEvent.click(screen.getByRole("button", {name: "Аннулировать счёт"}));
  const restart = await screen.findByRole("button", {name: "Начать новую сверку"});
  expect(api.fetchBasis).toHaveBeenCalledTimes(2);
  const rejectedAttempt = api.readJournal(scope).pending!;
  expect(rejectedAttempt.phase).toBe("cancel");
  fireEvent.click(restart);
  await waitFor(() => expect(api.readJournal(scope).pending).toBeNull());
  await waitFor(() => expect(screen.getByRole("button", {name: "Сохранить сверку исполнения"})).toBeEnabled());
  expect(api.readJournal(scope).review).toBeFalsy();
  expect(api.readJournal(scope).history.some(row => row.outcome === "rejected")).toBe(true);
  expect(api.sendAttempt).toHaveBeenCalledOnce();
  const next = makeReview();
  api.persist(next);
  expect(api.readJournal(scope).pending).toEqual(next);
  expect(next.body.request_key).not.toBe(rejectedAttempt.body.request_key);
});
