-- Draft-only expense history. Approval and command/effect provenance require
-- separate guards; immutability alone is not proof of an authorized operation.
CREATE TRIGGER immutable_expense_budget BEFORE UPDATE OR DELETE ON accounting.expense_budget
FOR EACH ROW EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER no_truncate_expense_budget BEFORE TRUNCATE ON accounting.expense_budget
FOR EACH STATEMENT EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER immutable_expense_budget_line BEFORE UPDATE OR DELETE ON accounting.expense_budget_line
FOR EACH ROW EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER no_truncate_expense_budget_line BEFORE TRUNCATE ON accounting.expense_budget_line
FOR EACH STATEMENT EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER immutable_expense_command_receipt BEFORE UPDATE OR DELETE ON accounting.expense_command_receipt
FOR EACH ROW EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER no_truncate_expense_command_receipt BEFORE TRUNCATE ON accounting.expense_command_receipt
FOR EACH STATEMENT EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER immutable_expense_budget_approval BEFORE UPDATE OR DELETE ON accounting.expense_budget_approval
FOR EACH ROW EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER no_truncate_expense_budget_approval BEFORE TRUNCATE ON accounting.expense_budget_approval
FOR EACH STATEMENT EXECUTE FUNCTION accounting.reject_history_mutation();

CREATE OR REPLACE FUNCTION accounting.guard_expense_months() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE cell jsonb;
BEGIN
  IF jsonb_typeof(NEW.months::jsonb) IS DISTINCT FROM 'array' OR jsonb_array_length(NEW.months::jsonb)<>12 THEN
    RAISE EXCEPTION 'Expense budget requires twelve monthly cells';
  END IF;
  FOR cell IN SELECT value FROM jsonb_array_elements(NEW.months::jsonb) LOOP
    IF cell='null'::jsonb THEN CONTINUE; END IF;
    IF jsonb_typeof(cell) IS DISTINCT FROM 'string' OR (cell#>>'{}') !~ '^(0|[1-9][0-9]{0,15})\.[0-9]{2}$' THEN
      RAISE EXCEPTION 'Expense month must be null or an exact nonnegative decimal string';
    END IF;
  END LOOP;
  RETURN NEW;
END $$;
CREATE TRIGGER valid_expense_months BEFORE INSERT ON accounting.expense_budget_line
FOR EACH ROW EXECUTE FUNCTION accounting.guard_expense_months();

-- Match the ledger's root-transaction proof: xmin cannot identify a parent
-- inserted inside a savepoint. A committed version must never gain new lines.
CREATE TABLE accounting.expense_budget_transaction (
  budget_id integer PRIMARY KEY REFERENCES accounting.expense_budget(id),
  root_transaction bigint NOT NULL
);
CREATE OR REPLACE FUNCTION accounting.guard_expense_budget_transaction() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF pg_trigger_depth() <> 2 OR NEW.root_transaction <> txid_current()
     OR NOT EXISTS (SELECT 1 FROM accounting.expense_budget WHERE id=NEW.budget_id) THEN
    RAISE EXCEPTION 'Expense budget transaction proof must be generated by its insert trigger';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER generated_expense_budget_transaction BEFORE INSERT ON accounting.expense_budget_transaction
FOR EACH ROW EXECUTE FUNCTION accounting.guard_expense_budget_transaction();
CREATE TRIGGER immutable_expense_budget_transaction BEFORE UPDATE OR DELETE ON accounting.expense_budget_transaction
FOR EACH ROW EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER no_truncate_expense_budget_transaction BEFORE TRUNCATE ON accounting.expense_budget_transaction
FOR EACH STATEMENT EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE OR REPLACE FUNCTION accounting.record_expense_budget_transaction() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO accounting.expense_budget_transaction(budget_id,root_transaction)
    VALUES(NEW.id,txid_current());
  RETURN NULL;
END $$;
CREATE TRIGGER record_expense_budget_transaction AFTER INSERT ON accounting.expense_budget
FOR EACH ROW EXECUTE FUNCTION accounting.record_expense_budget_transaction();
CREATE OR REPLACE FUNCTION accounting.guard_expense_budget_line_birth() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM accounting.expense_budget_transaction
                 WHERE budget_id=NEW.budget_id AND root_transaction=txid_current()) THEN
    RAISE EXCEPTION 'Cannot append to a committed expense budget version';
  END IF;
  IF EXISTS (SELECT 1 FROM accounting.expense_command_receipt
             WHERE organization_id=NEW.organization_id AND kind='budget'
               AND receipt::jsonb#>'{result,id}'=to_jsonb(NEW.budget_id)) THEN
    RAISE EXCEPTION 'Expense budget is sealed by its command receipt';
  END IF;
  RETURN NEW;
END $$;
-- Validate cells first, including on rejected late appends.
CREATE TRIGGER z_expense_budget_line_birth BEFORE INSERT ON accounting.expense_budget_line
FOR EACH ROW EXECUTE FUNCTION accounting.guard_expense_budget_line_birth();

CREATE UNIQUE INDEX expense_one_receipt_per_budget
ON accounting.expense_command_receipt (organization_id, (receipt::jsonb#>>'{result,id}'))
WHERE kind='budget';

CREATE UNIQUE INDEX expense_one_approval_per_budget
ON accounting.expense_budget_approval (organization_id, budget_id);

CREATE OR REPLACE FUNCTION accounting.expense_budget_payload(budget_key integer) RETURNS jsonb
LANGUAGE sql STABLE AS $$
  SELECT (to_jsonb(b)-'organization_id'-'created_at') || jsonb_build_object('lines',
    COALESCE((SELECT jsonb_agg(jsonb_build_object('article_id',l.article_id,
      'months',l.months,'article_snapshot',l.article_snapshot) ORDER BY l.article_id)
      FROM accounting.expense_budget_line l WHERE l.budget_id=b.id),'[]'::jsonb))
  FROM accounting.expense_budget b WHERE b.id=budget_key
$$;

CREATE OR REPLACE FUNCTION accounting.guard_expense_receipt() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE r jsonb:=NEW.receipt::jsonb; b accounting.expense_budget; a accounting.expense_budget_approval;
        expected jsonb; lines jsonb;
BEGIN
  IF NEW.kind NOT IN ('catalog','budget','budget_approval') OR jsonb_typeof(r) IS DISTINCT FROM 'object'
     OR r->'organization_id' IS DISTINCT FROM to_jsonb(NEW.organization_id)
     OR r->>'principal' IS DISTINCT FROM NEW.actor
     OR r->>'kind' IS DISTINCT FROM NEW.kind
     OR r->>'request_key' IS DISTINCT FROM NEW.request_key
     OR r#>>'{command,request_key}' IS DISTINCT FROM NEW.request_key
     OR r->>'command_hash' IS DISTINCT FROM NEW.command_hash
     OR accounting.financial_sha(r->'command') IS DISTINCT FROM NEW.command_hash
     OR accounting.financial_sha(r->'result') IS DISTINCT FROM r->>'result_digest'
     OR accounting.financial_sha(r-'receipt_digest') IS DISTINCT FROM r->>'receipt_digest' THEN
    RAISE EXCEPTION 'Expense receipt integrity mismatch';
  END IF;
  IF NEW.kind='budget' THEN
    SELECT * INTO b FROM accounting.expense_budget
      WHERE organization_id=NEW.organization_id AND to_jsonb(id)=r#>'{result,id}';
    IF b.id IS NULL OR NOT EXISTS (SELECT 1 FROM accounting.expense_budget_transaction
        WHERE budget_id=b.id AND root_transaction=txid_current()) THEN
      RAISE EXCEPTION 'Expense receipt requires a budget born in this transaction';
    END IF;
    expected:=accounting.expense_budget_payload(b.id);
    SELECT COALESCE(jsonb_agg(jsonb_build_object('article_id',l.article_id,'months',l.months)
      ORDER BY l.article_id),'[]'::jsonb) INTO lines
      FROM accounting.expense_budget_line l WHERE l.budget_id=b.id;
    IF jsonb_array_length(lines) NOT BETWEEN 1 AND 300 THEN
      RAISE EXCEPTION 'Expense budget requires between 1 and 300 lines';
    END IF;
    IF r->'result' IS DISTINCT FROM expected OR NEW.actor IS DISTINCT FROM b.actor
       OR r#>'{command,lines}' IS DISTINCT FROM lines
       OR r#>'{command,year}' IS DISTINCT FROM to_jsonb(b.year)
       OR r#>'{command,currency}' IS DISTINCT FROM to_jsonb(b.currency)
       OR r#>'{command,basis}' IS DISTINCT FROM to_jsonb(b.basis)
       OR r#>'{command,evidence}' IS DISTINCT FROM to_jsonb(b.evidence)
       OR r#>'{command,expected_revision}' IS DISTINCT FROM to_jsonb(b.revision-1)
       OR r#>'{command,expected_catalog_revision}' IS DISTINCT FROM to_jsonb(b.catalog_revision) THEN
      RAISE EXCEPTION 'Expense receipt does not match stored budget and command';
    END IF;
  END IF;
  IF NEW.kind='budget_approval' THEN
    IF jsonb_typeof(r#>'{result,budget_id}') IS DISTINCT FROM 'number'
       OR jsonb_typeof(r#>'{result,budget_revision}') IS DISTINCT FROM 'number'
       OR jsonb_typeof(r#>'{result,budget}') IS DISTINCT FROM 'object' THEN
      RAISE EXCEPTION 'Expense approval receipt has an invalid result';
    END IF;
    SELECT * INTO a FROM accounting.expense_budget_approval
      WHERE organization_id=NEW.organization_id
        AND budget_id=(r#>>'{result,budget_id}')::integer;
    IF a.id IS NULL THEN
      RAISE EXCEPTION 'Expense approval receipt requires its approval row';
    END IF;
    expected:=accounting.expense_budget_payload(a.budget_id);
    IF r#>'{result,budget}' IS DISTINCT FROM expected
       OR r#>>'{result,budget_revision}' IS DISTINCT FROM a.budget_revision::text
       OR r#>>'{result,approved_by}' IS DISTINCT FROM a.actor
       OR r#>>'{result,evidence}' IS DISTINCT FROM a.evidence
       OR r#>>'{result,approved_at}' IS DISTINCT FROM to_char(a.approved_at, 'YYYY-MM-DD"T"HH24:MI:SS')
       OR r#>>'{result,approval_digest}' IS DISTINCT FROM a.approval_digest
       OR accounting.financial_sha(r->'result'-'approval_digest') IS DISTINCT FROM a.approval_digest
       OR NEW.actor IS DISTINCT FROM a.actor
       OR r#>>'{command,budget_id}' IS DISTINCT FROM a.budget_id::text
       OR r#>>'{command,expected_revision}' IS DISTINCT FROM a.budget_revision::text
       OR r#>>'{command,evidence}' IS DISTINCT FROM a.evidence
       OR a.request_key IS DISTINCT FROM NEW.request_key THEN
      RAISE EXCEPTION 'Expense approval receipt does not match stored approval';
    END IF;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER valid_expense_receipt BEFORE INSERT ON accounting.expense_command_receipt
FOR EACH ROW EXECUTE FUNCTION accounting.guard_expense_receipt();

CREATE OR REPLACE FUNCTION accounting.require_expense_budget_receipt() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM accounting.expense_command_receipt
      WHERE organization_id=NEW.organization_id AND kind='budget'
        AND receipt::jsonb#>'{result,id}'=to_jsonb(NEW.id)) THEN
    RAISE EXCEPTION 'Expense budget requires its command receipt';
  END IF;
  RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER expense_budget_has_receipt AFTER INSERT ON accounting.expense_budget
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
EXECUTE FUNCTION accounting.require_expense_budget_receipt();

CREATE OR REPLACE FUNCTION accounting.require_expense_approval_receipt() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM accounting.expense_command_receipt
      WHERE organization_id=NEW.organization_id AND kind='budget_approval'
        AND request_key=NEW.request_key
        AND receipt::jsonb#>'{result,budget_id}'=to_jsonb(NEW.budget_id)) THEN
    RAISE EXCEPTION 'Expense budget approval requires its command receipt';
  END IF;
  RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER expense_approval_has_receipt AFTER INSERT ON accounting.expense_budget_approval
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
EXECUTE FUNCTION accounting.require_expense_approval_receipt();
