-- Financial close/reopen packages are single commands per organization/root transaction.
-- Calculation below uses ledger rows and immutable policy, never client-provided totals.
-- Envelope integrity is necessary but not sufficient: the independent package
-- and period-transition checks must also pass before public confirmation opens.
CREATE TRIGGER immutable_financial_close BEFORE UPDATE OR DELETE ON accounting.financial_close_receipt
FOR EACH ROW EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER no_truncate_financial_close BEFORE TRUNCATE ON accounting.financial_close_receipt
FOR EACH STATEMENT EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER immutable_financial_reopen BEFORE UPDATE OR DELETE ON accounting.financial_reopen_receipt
FOR EACH ROW EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER no_truncate_financial_reopen BEFORE TRUNCATE ON accounting.financial_reopen_receipt
FOR EACH STATEMENT EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER immutable_financial_reopen_item BEFORE UPDATE OR DELETE ON accounting.financial_reopen_item
FOR EACH ROW EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER no_truncate_financial_reopen_item BEFORE TRUNCATE ON accounting.financial_reopen_item
FOR EACH STATEMENT EXECUTE FUNCTION accounting.reject_history_mutation();

CREATE OR REPLACE FUNCTION accounting.financial_canonical(value jsonb) RETURNS text
LANGUAGE plpgsql IMMUTABLE STRICT AS $$
DECLARE result text;
BEGIN
  IF jsonb_typeof(value)='object' THEN
    SELECT '{'||coalesce(string_agg(to_jsonb(key)::text||':'||accounting.financial_canonical(v),',' ORDER BY key COLLATE "C"),'')||'}'
      INTO result FROM jsonb_each(value) AS x(key,v);
  ELSIF jsonb_typeof(value)='array' THEN
    SELECT '['||coalesce(string_agg(accounting.financial_canonical(v),',' ORDER BY n),'')||']'
      INTO result FROM jsonb_array_elements(value) WITH ORDINALITY AS x(v,n);
  ELSE result:=value::text;
  END IF;
  RETURN result;
END $$;
CREATE OR REPLACE FUNCTION accounting.financial_sha(value jsonb) RETURNS text
LANGUAGE sql IMMUTABLE STRICT AS $$
  SELECT encode(sha256(convert_to(accounting.financial_canonical(value),'UTF8')),'hex')
$$;

CREATE TABLE accounting.financial_receipt_transaction (
  kind text NOT NULL CHECK (kind IN ('close','reopen')),
  receipt_id integer NOT NULL,
  root_transaction bigint NOT NULL,
  organization_id integer NOT NULL REFERENCES accounting.organization(id),
  PRIMARY KEY(kind,receipt_id),
  CONSTRAINT financial_receipt_one_command_per_root UNIQUE(organization_id,root_transaction)
);
CREATE OR REPLACE FUNCTION accounting.guard_financial_receipt_transaction() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF pg_trigger_depth()<>2 OR NEW.root_transaction<>txid_current()
     OR (NEW.kind='close' AND NOT EXISTS(SELECT 1 FROM accounting.financial_close_receipt WHERE id=NEW.receipt_id AND organization_id=NEW.organization_id))
     OR (NEW.kind='reopen' AND NOT EXISTS(SELECT 1 FROM accounting.financial_reopen_receipt WHERE id=NEW.receipt_id AND organization_id=NEW.organization_id)) THEN
    RAISE EXCEPTION 'Financial receipt proof must be generated by its insert trigger';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER generated_financial_receipt_transaction BEFORE INSERT ON accounting.financial_receipt_transaction
FOR EACH ROW EXECUTE FUNCTION accounting.guard_financial_receipt_transaction();
CREATE TRIGGER immutable_financial_receipt_transaction BEFORE UPDATE OR DELETE ON accounting.financial_receipt_transaction
FOR EACH ROW EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER no_truncate_financial_receipt_transaction BEFORE TRUNCATE ON accounting.financial_receipt_transaction
FOR EACH STATEMENT EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE OR REPLACE FUNCTION accounting.record_financial_receipt_transaction() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO accounting.financial_receipt_transaction VALUES(
    CASE WHEN TG_TABLE_NAME='financial_close_receipt' THEN 'close' ELSE 'reopen' END,NEW.id,txid_current(),NEW.organization_id);
  RETURN NULL;
END $$;
CREATE TRIGGER record_financial_close_transaction AFTER INSERT ON accounting.financial_close_receipt
FOR EACH ROW EXECUTE FUNCTION accounting.record_financial_receipt_transaction();
CREATE TRIGGER record_financial_reopen_transaction AFTER INSERT ON accounting.financial_reopen_receipt
FOR EACH ROW EXECUTE FUNCTION accounting.record_financial_receipt_transaction();

CREATE OR REPLACE FUNCTION accounting.require_financial_entry_root(target_entry_id integer, org integer, actor_code text, op text)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  IF target_entry_id IS NOT NULL AND NOT EXISTS(
    SELECT 1 FROM accounting.entry e JOIN accounting.entry_transaction t ON t.entry_id=e.id
    WHERE e.id=target_entry_id AND e.organization_id=org AND e.actor=actor_code AND e.operation=op
      AND t.root_transaction=txid_current()) THEN
    RAISE EXCEPTION 'Financial entry must belong to the same organization and root transaction';
  END IF;
END $$;

CREATE OR REPLACE FUNCTION accounting.guard_financial_reopen_item() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE receipt accounting.financial_reopen_receipt; original accounting.financial_close_receipt;
BEGIN
  SELECT * INTO receipt FROM accounting.financial_reopen_receipt WHERE id=NEW.reopen_receipt_id;
  SELECT * INTO original FROM accounting.financial_close_receipt WHERE id=NEW.close_receipt_id;
  IF receipt.id IS NULL OR original.id IS NULL OR receipt.organization_id<>original.organization_id
     OR original.month<receipt.from_month OR NOT EXISTS(
       SELECT 1 FROM accounting.financial_receipt_transaction WHERE kind='reopen'
       AND receipt_id=receipt.id AND root_transaction=txid_current()) THEN
    RAISE EXCEPTION 'Financial reopening item must belong to its original receipt transaction and organization';
  END IF;
  PERFORM accounting.require_financial_entry_root(NEW.monthly_entry_id,receipt.organization_id,receipt.actor,'period_reopen');
  PERFORM accounting.require_financial_entry_root(NEW.annual_entry_id,receipt.organization_id,receipt.actor,'period_reopen');
  RETURN NEW;
END $$;
CREATE TRIGGER valid_financial_reopen_item BEFORE INSERT ON accounting.financial_reopen_item
FOR EACH ROW EXECUTE FUNCTION accounting.guard_financial_reopen_item();

CREATE OR REPLACE FUNCTION accounting.guard_financial_envelope() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE kind text; month_code text; row_json jsonb;
BEGIN
  row_json:=to_jsonb(NEW);
  PERFORM 1 FROM accounting.organization WHERE id=NEW.organization_id FOR UPDATE;
  IF EXISTS(SELECT 1 FROM accounting.financial_receipt_transaction t
    JOIN accounting.financial_close_receipt c ON t.kind='close' AND t.receipt_id=c.id
    WHERE t.root_transaction=txid_current() AND c.organization_id=NEW.organization_id)
    OR EXISTS(SELECT 1 FROM accounting.financial_receipt_transaction t
    JOIN accounting.financial_reopen_receipt r ON t.kind='reopen' AND t.receipt_id=r.id
    WHERE t.root_transaction=txid_current() AND r.organization_id=NEW.organization_id) THEN
    RAISE EXCEPTION 'Only one financial command per organization and root transaction is allowed';
  END IF;
  kind:=CASE WHEN TG_TABLE_NAME='financial_close_receipt' THEN 'close' ELSE 'reopen' END;
  month_code:=CASE WHEN kind='close' THEN row_json->>'month' ELSE row_json->>'from_month' END;
  IF NEW.request_key IS DISTINCT FROM (NEW.request_key::uuid)::text
     OR month_code !~ '^[0-9]{4}-(0[1-9]|1[0-2])$'
     OR btrim(NEW.actor)='' OR jsonb_typeof(NEW.command::jsonb) IS DISTINCT FROM 'object'
     OR jsonb_typeof(NEW.snapshot::jsonb) IS DISTINCT FROM 'object'
     OR NEW.command::jsonb->>'request_key' IS DISTINCT FROM NEW.request_key
     OR NEW.command::jsonb->>(CASE WHEN kind='close' THEN 'month' ELSE 'from_month' END) IS DISTINCT FROM month_code
     OR NEW.command_digest IS DISTINCT FROM accounting.financial_sha(NEW.command::jsonb)
     OR NEW.digest IS DISTINCT FROM accounting.financial_sha(jsonb_build_object(
         'organization_id',NEW.organization_id,'request_key',NEW.request_key,'kind',kind,
         'command',NEW.command,'command_digest',NEW.command_digest,'snapshot',NEW.snapshot,'actor',NEW.actor)) THEN
    RAISE EXCEPTION 'Invalid financial receipt envelope';
  END IF;
  IF kind='close' THEN
    PERFORM accounting.require_financial_entry_root((row_json->>'monthly_entry_id')::integer,NEW.organization_id,NEW.actor,'period_close');
    PERFORM accounting.require_financial_entry_root((row_json->>'annual_entry_id')::integer,NEW.organization_id,NEW.actor,'period_close');
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER valid_financial_close_envelope BEFORE INSERT ON accounting.financial_close_receipt
FOR EACH ROW EXECUTE FUNCTION accounting.guard_financial_envelope();
CREATE TRIGGER valid_financial_reopen_envelope BEFORE INSERT ON accounting.financial_reopen_receipt
FOR EACH ROW EXECUTE FUNCTION accounting.guard_financial_envelope();

CREATE OR REPLACE FUNCTION accounting.financial_close_calculation(
  org integer, month_code text, excluded integer[], org_generation integer, period_generation integer
) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE first_day date; last_day date; initial accounting.policy; settings jsonb;
        policies jsonb; accounts jsonb; source_rows jsonb; codes text[]; monthly jsonb:='[]'; annual jsonb:='[]';
        b record; a jsonb; code text; amount text; source_side text; target_side text;
BEGIN
  IF month_code !~ '^[0-9]{4}-(0[1-9]|1[0-2])$' THEN RAISE EXCEPTION 'Invalid financial month'; END IF;
  first_day:=(month_code||'-01')::date;
  last_day:=(first_day+interval '1 month - 1 day')::date;
  SELECT * INTO initial FROM accounting.policy WHERE organization_id=org AND effective_from<=first_day
    ORDER BY effective_from DESC LIMIT 1;
  settings:=initial.financial_closing::jsonb;
  IF initial.id IS NULL OR settings IS NULL OR settings='null'::jsonb THEN
    RAISE EXCEPTION 'Financial closing policy must cover the whole month';
  END IF;
  IF EXISTS(SELECT 1 FROM accounting.policy WHERE organization_id=org AND effective_from<=last_day
     AND (effective_from>first_day OR id=initial.id)
     AND financial_closing::jsonb IS DISTINCT FROM settings) THEN
    RAISE EXCEPTION 'Changed financial closing policy';
  END IF;
  SELECT jsonb_agg(jsonb_build_object('id',id,'effective_from',effective_from::text,
    'normative_verified',normative_verified,'settings',financial_closing) ORDER BY effective_from DESC)
    INTO policies FROM accounting.policy WHERE organization_id=org AND effective_from<=last_day
      AND (effective_from>first_day OR id=initial.id);
  IF settings->>'opening_balance_treatment' NOT IN ('include','exclude')
     OR jsonb_typeof(settings->'monthly_accounts')<>'array'
     OR jsonb_array_length(settings->'monthly_accounts') NOT BETWEEN 1 AND 200
     OR (settings->>'year_end_month')::integer NOT BETWEEN 1 AND 12 THEN
    RAISE EXCEPTION 'Unsupported financial closing settings';
  END IF;
  SELECT array_agg(v) INTO codes FROM (
    SELECT jsonb_array_elements_text(settings->'monthly_accounts') v
    UNION ALL SELECT settings->>'result_account' UNION ALL SELECT settings->>'retained_earnings_account') x;
  IF cardinality(codes)<>(SELECT count(DISTINCT v) FROM unnest(codes) v)
     OR EXISTS(SELECT 1 FROM unnest(codes) v WHERE v IS NULL OR v !~ '^[0-9]+(\.[0-9]+)*$') THEN
    RAISE EXCEPTION 'Financial closing account roles must be distinct';
  END IF;
  SELECT jsonb_object_agg(x.code,to_jsonb(x)) INTO accounts FROM (
    SELECT DISTINCT ON (a.code) a.* FROM accounting.account a WHERE a.organization_id=org AND a.valid_from<=last_day
      AND a.code=ANY(codes) ORDER BY a.code,a.valid_from DESC,a.id DESC) x;
  FOREACH code IN ARRAY codes LOOP
    a:=accounts->code;
    IF a IS NULL OR (a->>'cash')::boolean OR (a->>'quantity_tracking')::boolean
       OR (a->>'currency_tracking')::boolean
       OR (code=settings->>'result_account' AND a->>'category'<>'income')
       OR (code=settings->>'retained_earnings_account' AND a->>'category'<>'equity')
       OR (settings->'monthly_accounts' ? code AND a->>'category' NOT IN ('income','expense')) THEN
      RAISE EXCEPTION 'Unsupported financial closing account %',code;
    END IF;
    IF code IN (settings->>'result_account',settings->>'retained_earnings_account') THEN
      IF ARRAY(SELECT jsonb_array_elements_text(a->'required_dimensions') ORDER BY 1)
         IS DISTINCT FROM ARRAY(SELECT jsonb_object_keys(settings->
             CASE WHEN code=settings->>'result_account' THEN 'result_dimensions' ELSE 'retained_dimensions' END) ORDER BY 1) THEN
        RAISE EXCEPTION 'Financial recipient analytics mismatch';
      END IF;
    END IF;
  END LOOP;
  IF EXISTS(SELECT 1 FROM accounting.financial_close_receipt c
      JOIN accounting.policy p ON p.id=(c.snapshot::jsonb->'preview'->>'policy_id')::integer
      WHERE c.organization_id=org AND c.month<month_code
      AND NOT EXISTS(SELECT 1 FROM accounting.financial_reopen_item r WHERE r.close_receipt_id=c.id)
      AND (p.financial_closing::jsonb-'reference') IS DISTINCT FROM (settings-'reference')) THEN
    RAISE EXCEPTION 'Financial policy transition requires reopening';
  END IF;
  IF EXISTS(SELECT 1 FROM accounting.entry e JOIN accounting.line l ON l.entry_id=e.id
      WHERE e.organization_id=org AND e.posting_date<=last_day AND l.account_code=ANY(codes)
      AND NOT(e.id=ANY(excluded)) AND NOT(e.opening AND settings->>'opening_balance_treatment'='exclude')
      AND (l.category IS DISTINCT FROM (accounts->l.account_code->>'category') OR l.cash
        OR l.currency<>'BYN' OR l.quantity IS NOT NULL OR NOT(l.dimensions::jsonb ?&
          ARRAY(SELECT jsonb_array_elements_text(accounts->l.account_code->'required_dimensions'))))) THEN
    RAISE EXCEPTION 'Historical closing analytics or account classification require reconciliation';
  END IF;
  SELECT coalesce(jsonb_agg(jsonb_build_object('entry_id',e.id,'entry_digest',e.digest,'line_id',l.id,
      'account_id',l.account_id,'account_code',l.account_code,'category',l.category,'cash',l.cash,
      'side',l.side,'amount',l.amount::text,'dimensions',l.dimensions,'currency',l.currency,
      'quantity',l.quantity::text,'opening',e.opening,'posting_date',e.posting_date::text)
      ORDER BY e.id,l.id),'[]') INTO source_rows
    FROM accounting.entry e JOIN accounting.line l ON l.entry_id=e.id
    WHERE e.organization_id=org AND e.posting_date<=last_day AND l.account_code=ANY(codes)
      AND NOT(e.id=ANY(excluded));
  FOR b IN SELECT v->>'account_code' code,v->'dimensions' dims,
      sum((v->>'amount')::numeric*CASE WHEN v->>'side'='debit' THEN 1 ELSE -1 END) balance
      FROM jsonb_array_elements(source_rows) v
      WHERE settings->'monthly_accounts' ? (v->>'account_code')
        AND NOT((v->>'opening')::boolean AND settings->>'opening_balance_treatment'='exclude')
      GROUP BY v->>'account_code',v->'dimensions'
      ORDER BY (v->>'account_code') COLLATE "C",accounting.financial_canonical(v->'dimensions') COLLATE "C"
  LOOP
    IF b.balance=0 THEN CONTINUE; END IF;
    amount:=abs(b.balance)::numeric(20,2)::text;
    source_side:=CASE WHEN b.balance>0 THEN 'credit' ELSE 'debit' END;
    target_side:=CASE WHEN b.balance>0 THEN 'debit' ELSE 'credit' END;
    monthly:=monthly||jsonb_build_array(
      jsonb_build_object('account',b.code,'dimensions',b.dims,'side',source_side,'amount',amount),
      jsonb_build_object('account',settings->>'result_account','dimensions',settings->'result_dimensions','side',target_side,'amount',amount));
  END LOOP;
  IF extract(month FROM first_day)=(settings->>'year_end_month')::integer THEN
    FOR b IN SELECT dims,sum(balance) balance FROM (
        SELECT v->'dimensions' dims,(v->>'amount')::numeric*CASE WHEN v->>'side'='debit' THEN 1 ELSE -1 END balance
        FROM jsonb_array_elements(source_rows) v WHERE v->>'account_code'=settings->>'result_account'
          AND NOT((v->>'opening')::boolean AND settings->>'opening_balance_treatment'='exclude')
        UNION ALL SELECT v->'dimensions',(v->>'amount')::numeric*CASE WHEN v->>'side'='debit' THEN 1 ELSE -1 END
        FROM jsonb_array_elements(monthly) v WHERE v->>'account'=settings->>'result_account') x
      GROUP BY dims ORDER BY accounting.financial_canonical(dims) COLLATE "C"
    LOOP
      IF b.balance=0 THEN CONTINUE; END IF;
      amount:=abs(b.balance)::numeric(20,2)::text;
      annual:=annual||jsonb_build_array(
        jsonb_build_object('account',settings->>'result_account','dimensions',b.dims,
          'side',CASE WHEN b.balance>0 THEN 'credit' ELSE 'debit' END,'amount',amount),
        jsonb_build_object('account',settings->>'retained_earnings_account','dimensions',settings->'retained_dimensions',
          'side',CASE WHEN b.balance>0 THEN 'debit' ELSE 'credit' END,'amount',amount));
    END LOOP;
  END IF;
  SELECT jsonb_agg(jsonb_build_object('id',(v->>'id')::integer,'code',k,'category',v->>'category',
      'dimensions',v->'required_dimensions') ORDER BY k COLLATE "C") INTO accounts FROM jsonb_each(accounts) x(k,v);
  RETURN jsonb_build_object('organization_id',org,'month',month_code,'organization_generation',org_generation,
    'period_generation',period_generation,'policies',policies,'accounts',accounts,'source_lines',source_rows,
    'monthly_lines',monthly,'annual_lines',annual);
END $$;


-- Validate the complete close calculation at receipt insertion. Deferred period
-- transition and reopening-cascade certification are separate required guards.
CREATE OR REPLACE FUNCTION accounting.guard_financial_close_calculation() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE ids integer[]; transfer_count integer; org_generation integer; period_row accounting.period;
        basis jsonb; plan jsonb; phase text; planned jsonb; expected_body jsonb; actual_body jsonb;
        entry_row accounting.entry; target_id integer; last_day date;
BEGIN
  ids:=array_remove(ARRAY[NEW.monthly_entry_id,NEW.annual_entry_id],NULL);
  transfer_count:=cardinality(ids);
  SELECT generation INTO org_generation FROM accounting.organization WHERE id=NEW.organization_id FOR UPDATE;
  SELECT * INTO period_row FROM accounting.period WHERE organization_id=NEW.organization_id AND month=NEW.month;
  IF period_row.id IS NULL OR NOT period_row.closed OR period_row.closed_generation IS DISTINCT FROM period_row.generation
     OR period_row.evidence::jsonb IS DISTINCT FROM NEW.command::jsonb->'evidence'
     OR NEW.command::jsonb->>'expected_generation' IS DISTINCT FROM (period_row.generation-transfer_count)::text
     OR NEW.snapshot::jsonb->>'closed_generation' IS DISTINCT FROM period_row.generation::text THEN
    RAISE EXCEPTION 'Financial closing period does not match the reviewed command';
  END IF;
  basis:=accounting.financial_close_calculation(NEW.organization_id,NEW.month,ids,
      org_generation-transfer_count,period_row.generation-transfer_count);
  plan:=NEW.snapshot::jsonb->'preview';
  IF plan->'basis' IS DISTINCT FROM basis OR plan->>'basis_digest' IS DISTINCT FROM accounting.financial_sha(basis)
     OR NEW.command::jsonb->>'expected_basis_digest' IS DISTINCT FROM accounting.financial_sha(basis)
     OR plan->>'organization_id' IS DISTINCT FROM NEW.organization_id::text
     OR plan->>'month' IS DISTINCT FROM NEW.month
     OR plan->>'period_generation' IS DISTINCT FROM (period_row.generation-transfer_count)::text
     OR plan->>'policy_id' IS DISTINCT FROM basis->'policies'->0->>'id'
     OR EXISTS(SELECT 1 FROM jsonb_array_elements(basis->'policies') p WHERE p->>'normative_verified' IS DISTINCT FROM 'true') THEN
    RAISE EXCEPTION 'Financial closing basis differs from independent ledger calculation';
  END IF;
  last_day:=((NEW.month||'-01')::date+interval '1 month - 1 day')::date;
  FOREACH phase IN ARRAY ARRAY['monthly','annual'] LOOP
    target_id:=CASE WHEN phase='monthly' THEN NEW.monthly_entry_id ELSE NEW.annual_entry_id END;
    planned:=basis->(phase||'_lines');
    IF plan->(phase||'_lines') IS DISTINCT FROM planned
       OR NEW.snapshot::jsonb->(phase||'_entry_id') IS DISTINCT FROM coalesce(to_jsonb(target_id),'null'::jsonb)
       OR (jsonb_array_length(planned)>0) IS DISTINCT FROM (target_id IS NOT NULL) THEN
      RAISE EXCEPTION 'Financial closing transfer membership differs from calculation';
    END IF;
    IF target_id IS NULL THEN CONTINUE; END IF;
    IF EXISTS(SELECT 1 FROM accounting.line l WHERE l.entry_id=target_id AND NOT EXISTS(
      SELECT 1 FROM jsonb_array_elements(basis->'accounts') a
      WHERE a->>'code'=l.account_code AND (a->>'id')::integer=l.account_id)) THEN
      RAISE EXCEPTION 'Financial closing line must use the effective account version from its basis';
    END IF;
    SELECT * INTO entry_row FROM accounting.entry WHERE id=target_id;
    SELECT jsonb_agg(v||jsonb_build_object('currency','BYN','original_amount',NULL,'rate',NULL,
        'rate_scale',NULL,'rate_date',NULL,'rate_source',NULL,'quantity',NULL,'cash_activity',NULL) ORDER BY n)
      INTO planned FROM jsonb_array_elements(planned) WITH ORDINALITY x(v,n);
    expected_body:=jsonb_build_object('source','financial-close:'||NEW.request_key||':'||phase,'source_version',1,
        'operation','period_close','document_date',last_day,'operation_date',last_day,'posting_date',last_day,
        'policy_id',(plan->>'policy_id')::integer,'rule_version','financial-closing-v1:'||phase,
        'explanation','Financial closing '||NEW.month||': '||phase,'opening',false,'correction_of',NULL,'lines',planned);
    SELECT (to_jsonb(entry_row)-ARRAY['id','organization_id','digest','actor','created_at'])||jsonb_build_object('lines',
      jsonb_agg((to_jsonb(l)-ARRAY['id','entry_id','account_id','account_code','account_title','category','cash'])||
        jsonb_build_object('account',l.account_code,'amount',l.amount::text) ORDER BY l.id))
      INTO actual_body FROM accounting.line l WHERE l.entry_id=target_id;
    IF actual_body IS DISTINCT FROM expected_body OR entry_row.digest IS DISTINCT FROM accounting.financial_sha(expected_body) THEN
      RAISE EXCEPTION 'Financial closing posting differs from independent calculation';
    END IF;
  END LOOP;
  RETURN NEW;
END $$;
CREATE TRIGGER verify_financial_close_calculation BEFORE INSERT ON accounting.financial_close_receipt
FOR EACH ROW EXECUTE FUNCTION accounting.guard_financial_close_calculation();

CREATE OR REPLACE FUNCTION accounting.guard_finalized_close_lines() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF EXISTS(SELECT 1 FROM accounting.financial_close_receipt
    WHERE monthly_entry_id=NEW.entry_id OR annual_entry_id=NEW.entry_id) THEN
    RAISE EXCEPTION 'Financial closing lines cannot be appended after receipt validation';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER finalized_financial_close_lines BEFORE INSERT ON accounting.line
FOR EACH ROW EXECUTE FUNCTION accounting.guard_finalized_close_lines();


CREATE OR REPLACE FUNCTION accounting.financial_posting_body(target_entry_id integer) RETURNS jsonb
LANGUAGE sql STABLE AS $$
  SELECT (to_jsonb(e)-ARRAY['id','organization_id','digest','actor','created_at'])||jsonb_build_object('lines',
    (SELECT jsonb_agg((to_jsonb(l)-ARRAY['id','entry_id','account_id','account_code','account_title','category','cash'])||
      jsonb_build_object('account',l.account_code,'amount',l.amount::text) ORDER BY l.id)
     FROM accounting.line l WHERE l.entry_id=e.id)) FROM accounting.entry e WHERE e.id=target_entry_id
$$;
CREATE OR REPLACE FUNCTION accounting.validate_financial_reversal_bodies(target_receipt_id integer) RETURNS void
LANGUAGE plpgsql AS $$
DECLARE receipt accounting.financial_reopen_receipt; items jsonb; item accounting.financial_reopen_item; original accounting.financial_close_receipt;
        phase text; source_id integer; target_id integer; expected jsonb; reversed_lines jsonb;
BEGIN
  SELECT * INTO STRICT receipt FROM accounting.financial_reopen_receipt WHERE id=target_receipt_id;
  IF EXISTS(SELECT 1 FROM accounting.financial_close_receipt c
    WHERE c.organization_id=receipt.organization_id AND c.month>=receipt.from_month
      AND NOT EXISTS(SELECT 1 FROM accounting.financial_reopen_item i WHERE i.close_receipt_id=c.id)) THEN
    RAISE EXCEPTION 'Financial reopening must include every active close from the selected month';
  END IF;
  SELECT coalesce(jsonb_agg(jsonb_build_object('close_receipt_id',i.close_receipt_id,
    'monthly_entry_id',i.monthly_entry_id,'annual_entry_id',i.annual_entry_id) ORDER BY i.close_receipt_id),'[]'::jsonb)
    INTO items FROM accounting.financial_reopen_item i WHERE i.reopen_receipt_id=receipt.id;
  IF items IS DISTINCT FROM receipt.snapshot::jsonb->'items' THEN
    RAISE EXCEPTION 'Financial reopening item list differs from its receipt';
  END IF;
  FOR item IN SELECT * FROM accounting.financial_reopen_item WHERE reopen_receipt_id=receipt.id LOOP
    SELECT * INTO original FROM accounting.financial_close_receipt WHERE id=item.close_receipt_id;
    FOREACH phase IN ARRAY ARRAY['monthly','annual'] LOOP
      source_id:=CASE WHEN phase='monthly' THEN original.monthly_entry_id ELSE original.annual_entry_id END;
      target_id:=CASE WHEN phase='monthly' THEN item.monthly_entry_id ELSE item.annual_entry_id END;
      IF (source_id IS NULL) IS DISTINCT FROM (target_id IS NULL) THEN
        RAISE EXCEPTION 'Financial reopening has an incomplete reversal';
      END IF;
      IF source_id IS NULL THEN CONTINUE; END IF;
      expected:=accounting.financial_posting_body(source_id);
      SELECT jsonb_agg(v||jsonb_build_object('side',CASE WHEN v->>'side'='debit' THEN 'credit' ELSE 'debit' END) ORDER BY n)
        INTO reversed_lines FROM jsonb_array_elements(expected->'lines') WITH ORDINALITY x(v,n);
      expected:=expected||jsonb_build_object('source','financial-reopen:'||receipt.request_key||':'||source_id::text,
        'operation','period_reopen','correction_of',source_id,'rule_version','financial-reopening-v1',
        'explanation',receipt.command::jsonb->>'reason','lines',reversed_lines);
      IF expected IS DISTINCT FROM accounting.financial_posting_body(target_id)
         OR NOT EXISTS(SELECT 1 FROM accounting.entry WHERE id=target_id AND digest=accounting.financial_sha(expected))
         OR EXISTS(SELECT 1 FROM
           (SELECT account_id,row_number() OVER (ORDER BY id) n FROM accounting.line WHERE entry_id=source_id) a
           FULL JOIN (SELECT account_id,row_number() OVER (ORDER BY id) n FROM accounting.line WHERE entry_id=target_id) b USING(n)
           WHERE a.account_id IS DISTINCT FROM b.account_id) THEN
        RAISE EXCEPTION 'Financial reopening must exactly reverse the original posting and account versions';
      END IF;
    END LOOP;
  END LOOP;
  RETURN;
END $$;
CREATE OR REPLACE FUNCTION accounting.guard_financial_reversal_bodies() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE target integer;
BEGIN
  IF TG_TABLE_NAME='financial_reopen_receipt' THEN
    PERFORM accounting.validate_financial_reversal_bodies(NEW.id);
  ELSIF TG_TABLE_NAME='financial_reopen_item' THEN
    PERFORM accounting.validate_financial_reversal_bodies(NEW.reopen_receipt_id);
  ELSE
    FOR target IN SELECT DISTINCT reopen_receipt_id FROM accounting.financial_reopen_item
      WHERE monthly_entry_id=NEW.entry_id OR annual_entry_id=NEW.entry_id LOOP
      PERFORM accounting.validate_financial_reversal_bodies(target);
    END LOOP;
  END IF;
  RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER verify_financial_reversal_bodies AFTER INSERT ON accounting.financial_reopen_receipt
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION accounting.guard_financial_reversal_bodies();

CREATE CONSTRAINT TRIGGER verify_financial_reversal_item AFTER INSERT ON accounting.financial_reopen_item
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION accounting.guard_financial_reversal_bodies();
CREATE CONSTRAINT TRIGGER verify_financial_reversal_line AFTER INSERT ON accounting.line
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION accounting.guard_financial_reversal_bodies();
