-- CRM-ACC-001 migration body: install with the accounting schema, never on finance tables.
CREATE OR REPLACE FUNCTION accounting.reject_history_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'Accounting history is immutable: %', TG_TABLE_NAME;
END $$;

CREATE TRIGGER immutable_shipment_preparation_draft BEFORE UPDATE OR DELETE ON accounting.shipment_preparation_draft
FOR EACH ROW EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER no_truncate_shipment_preparation_draft BEFORE TRUNCATE ON accounting.shipment_preparation_draft
FOR EACH STATEMENT EXECUTE FUNCTION accounting.reject_history_mutation();

CREATE TRIGGER immutable_entry BEFORE UPDATE OR DELETE ON accounting.entry
FOR EACH ROW EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER immutable_shipment_accounting_receipt BEFORE UPDATE OR DELETE ON accounting.shipment_accounting_receipt
FOR EACH ROW EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER immutable_line BEFORE UPDATE OR DELETE ON accounting.line
FOR EACH ROW EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER immutable_account BEFORE UPDATE OR DELETE ON accounting.account
FOR EACH ROW EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER immutable_policy BEFORE UPDATE OR DELETE ON accounting.policy
FOR EACH ROW EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER immutable_seller_profile BEFORE UPDATE OR DELETE ON accounting.seller_profile
FOR EACH ROW EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER no_truncate_seller_profile BEFORE TRUNCATE ON accounting.seller_profile
FOR EACH STATEMENT EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER immutable_audit BEFORE UPDATE OR DELETE ON accounting.audit
FOR EACH ROW EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER immutable_source_binding BEFORE UPDATE OR DELETE ON accounting.source_binding
FOR EACH ROW EXECUTE FUNCTION accounting.reject_history_mutation();

-- A subtransaction xmin is not the root transaction identity. Record a SQL-only
-- birth proof so entry + lines may use real savepoints without permitting late appends.
CREATE TABLE accounting.entry_transaction (
  entry_id integer PRIMARY KEY REFERENCES accounting.entry(id),
  root_transaction bigint NOT NULL
);
CREATE OR REPLACE FUNCTION accounting.guard_entry_transaction() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF pg_trigger_depth() <> 2 OR NEW.root_transaction <> txid_current()
     OR NOT EXISTS (SELECT 1 FROM accounting.entry WHERE id=NEW.entry_id) THEN
    RAISE EXCEPTION 'Entry transaction proof must be generated by its insert trigger';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER generated_entry_transaction BEFORE INSERT ON accounting.entry_transaction
FOR EACH ROW EXECUTE FUNCTION accounting.guard_entry_transaction();
CREATE TRIGGER immutable_entry_transaction BEFORE UPDATE OR DELETE ON accounting.entry_transaction
FOR EACH ROW EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER no_truncate_entry_transaction BEFORE TRUNCATE ON accounting.entry_transaction
FOR EACH STATEMENT EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE OR REPLACE FUNCTION accounting.record_entry_transaction() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO accounting.entry_transaction(entry_id,root_transaction) VALUES(NEW.id,txid_current());
  RETURN NULL;
END $$;
CREATE TRIGGER record_entry_transaction AFTER INSERT ON accounting.entry
FOR EACH ROW EXECUTE FUNCTION accounting.record_entry_transaction();
CREATE TRIGGER no_truncate_entry BEFORE TRUNCATE ON accounting.entry
FOR EACH STATEMENT EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER no_truncate_line BEFORE TRUNCATE ON accounting.line
FOR EACH STATEMENT EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER no_truncate_account BEFORE TRUNCATE ON accounting.account
FOR EACH STATEMENT EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER no_truncate_policy BEFORE TRUNCATE ON accounting.policy
FOR EACH STATEMENT EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER no_truncate_audit BEFORE TRUNCATE ON accounting.audit
FOR EACH STATEMENT EXECUTE FUNCTION accounting.reject_history_mutation();
CREATE TRIGGER no_truncate_source_binding BEFORE TRUNCATE ON accounting.source_binding
FOR EACH STATEMENT EXECUTE FUNCTION accounting.reject_history_mutation();

CREATE OR REPLACE FUNCTION accounting.guard_entry_insert() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE policy_org integer;
BEGIN
  PERFORM 1 FROM accounting.organization WHERE id = NEW.organization_id FOR UPDATE;
  SELECT organization_id INTO policy_org FROM accounting.policy WHERE id = NEW.policy_id;
  IF policy_org IS DISTINCT FROM NEW.organization_id THEN
    RAISE EXCEPTION 'Policy belongs to another organization';
  END IF;
  IF EXISTS (SELECT 1 FROM accounting.period WHERE organization_id = NEW.organization_id
             AND month >= to_char(NEW.posting_date, 'YYYY-MM') AND closed) THEN
    RAISE EXCEPTION 'Closed accounting period';
  END IF;
  IF NEW.correction_of IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM accounting.entry WHERE id = NEW.correction_of
      AND organization_id = NEW.organization_id AND posting_date <= NEW.posting_date
  ) THEN RAISE EXCEPTION 'Invalid correction reference'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER guard_entry_insert BEFORE INSERT ON accounting.entry
FOR EACH ROW EXECUTE FUNCTION accounting.guard_entry_insert();

CREATE OR REPLACE FUNCTION accounting.guard_line_insert() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE e accounting.entry; a accounting.account; entry_xid bigint;
BEGIN
  SELECT * INTO e FROM accounting.entry WHERE id = NEW.entry_id;
  -- The entry and its lines must be created in the same transaction.
  SELECT root_transaction INTO entry_xid FROM accounting.entry_transaction WHERE entry_id = NEW.entry_id;
  IF entry_xid IS DISTINCT FROM txid_current() THEN
    RAISE EXCEPTION 'Cannot append lines to a committed entry';
  END IF;
  SELECT * INTO a FROM accounting.account WHERE id = NEW.account_id;
  IF a.organization_id IS DISTINCT FROM e.organization_id OR a.valid_from > e.posting_date THEN
    RAISE EXCEPTION 'Account organization or effective date mismatch';
  END IF;
  IF NEW.category IS DISTINCT FROM a.category OR NEW.cash IS DISTINCT FROM a.cash
     OR NEW.account_code IS DISTINCT FROM a.code OR NEW.account_title IS DISTINCT FROM a.title THEN
    RAISE EXCEPTION 'Account snapshot mismatch';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER guard_line_insert BEFORE INSERT ON accounting.line
FOR EACH ROW EXECUTE FUNCTION accounting.guard_line_insert();

CREATE OR REPLACE FUNCTION accounting.check_entry_balance() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE delta numeric; line_count integer;
BEGIN
  SELECT count(*), coalesce(sum(CASE WHEN category = 'off_balance' THEN 0
    WHEN side = 'debit' THEN amount ELSE -amount END), 0)
  INTO line_count, delta FROM accounting.line WHERE entry_id = NEW.id;
  IF line_count = 0 OR delta <> 0 THEN
    RAISE EXCEPTION 'Empty or unbalanced accounting entry %', NEW.id;
  END IF;
  RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER balanced_entry AFTER INSERT ON accounting.entry
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION accounting.check_entry_balance();

-- Completeness registry may advance only with a new source version or its matching entry.
CREATE OR REPLACE FUNCTION accounting.guard_source_control() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Source completeness records cannot be deleted';
  END IF;
  IF TG_OP = 'INSERT' THEN
    IF NEW.version <> 1 OR NEW.entry_id IS NOT NULL THEN
      RAISE EXCEPTION 'Source completeness must start pending at version 1';
    END IF;
  ELSE
    -- A physical act is immutable; corrections must be separate operations.
    IF OLD.source LIKE 'wms:physical-shipment:%' AND
       (NEW.version IS DISTINCT FROM OLD.version OR NEW.month IS DISTINCT FROM OLD.month) THEN
      RAISE EXCEPTION 'Physical shipment source identity is immutable';
    END IF;
    IF NEW.organization_id IS DISTINCT FROM OLD.organization_id OR NEW.source IS DISTINCT FROM OLD.source
       OR OLD.entry_id IS NOT NULL THEN
      RAISE EXCEPTION 'Resolved source completeness is immutable';
    END IF;
    IF NEW.entry_id IS NULL THEN
      IF NEW.version <> OLD.version + 1 THEN
        RAISE EXCEPTION 'Source completeness requires the next version';
      END IF;
    ELSIF NEW.version <> OLD.version OR NEW.month <> OLD.month THEN
      RAISE EXCEPTION 'Resolving a source cannot change its version or month';
    END IF;
  END IF;
  IF NEW.entry_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM accounting.entry e WHERE e.id = NEW.entry_id
      AND e.organization_id = NEW.organization_id AND e.source = NEW.source
      AND e.source_version = NEW.version AND to_char(e.posting_date, 'YYYY-MM') = NEW.month
  ) THEN
    RAISE EXCEPTION 'Source completeness requires its matching posted entry';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER guard_source_control BEFORE INSERT OR UPDATE OR DELETE ON accounting.source_control
FOR EACH ROW EXECUTE FUNCTION accounting.guard_source_control();
