import { execFileSync } from "node:child_process";
import { expect, test } from "@playwright/test";

test("импорт выписки сохраняет аналитику из формы", async ({ page }, testInfo) => {
  const stamp = Date.now();
  const response = await page.request.post("/api/accounting/organizations", { data: { name: `E2E bank dimensions ${stamp}`, unp: String(stamp).slice(-9) } });
  expect(response.ok(), await response.text()).toBeTruthy();
  const org = await response.json();
  execFileSync("python", ["e2e/seed_bank_import.py", String(org.id)], { timeout: 30000 });
  await page.goto("/erp/accounting");
  await page.getByLabel("Организация", { exact: true }).selectOption(String(org.id));
  await page.getByRole("button", { name: "Импорт выписки", exact: true }).click();
  const row = page.getByRole("row").filter({ hasText: `E2E-BANK-${org.id}` });
  await row.getByRole("button", { name: "Выбрать", exact: true }).click();
  await page.getByLabel("Расчёты: counterparty").fill("BUYER-E2E");
  await page.getByLabel("Расчёты: contract").fill("CONTRACT-E2E");
  await page.getByRole("button", { name: "Рассчитать проводки", exact: true }).click();
  await expect(page.getByText("contract: CONTRACT-E2E", { exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("bank-analytics-preview.png"), fullPage: true });
  const confirmed = page.waitForResponse(r => r.url().endsWith("/bank-import/confirm") && r.request().method() === "POST");
  await page.getByRole("button", { name: "Подтвердить импорт", exact: true }).click();
  const saved = await confirmed;
  expect(saved.ok(), await saved.text()).toBeTruthy();
  const receipt = await saved.json();
  const entryResponse = await page.request.get(`/api/accounting/organizations/${org.id}/entries/${receipt.entry_id}`);
  expect(entryResponse.ok(), await entryResponse.text()).toBeTruthy();
  const entry = await entryResponse.json();
  expect(entry.lines.find((line: { account_code: string }) => line.account_code === "62").dimensions).toMatchObject({ counterparty: "BUYER-E2E", contract: "CONTRACT-E2E" });
  await expect(row).toContainText("Проведено");
  await row.getByRole("button", { name: "Открыть проводку" }).click();
  const card = page.getByRole("region", { name: "Карточка проводки" });
  await expect(card.getByRole("heading", { name: `Операция № ${receipt.entry_id}` })).toBeVisible();
  await expect(card).toContainText("CONTRACT-E2E");
  await card.screenshot({ path: testInfo.outputPath("bank-entry-card.png") });
});
