import { expect, test } from "@playwright/test";
import { writeFile } from "node:fs/promises";

test("own: клиент → контакт → сделка → задача/история → счёт под заказ и чужой доступ", async ({ page, context, browser, baseURL }) => {
  test.setTimeout(180_000);
  await context.clearCookies();
  await page.goto("/login");
  await page.getByLabel("Сотрудник").selectOption("e2e_owner");
  await page.getByRole("button", { name: "Войти", exact: true }).click();
  await expect(page).not.toHaveURL(/\/login/);
  const name = `OWN E2E ${Date.now()}`;
  await page.goto("/crm/clients");
  await page.getByRole("button", { name: "Новый клиент", exact: true }).click();
  const clientForm = page.getByRole("form", { name: "Новый клиент CRM" });
  await clientForm.getByLabel("Название клиента", { exact: true }).fill(name);
  await expect(clientForm.getByRole("combobox", { name: "Ответственный", exact: true })).toHaveValue("2901");
  const createdClient = page.waitForResponse((r) => r.url().endsWith('/api/sales/clients') && r.request().method() === 'POST');
  await clientForm.getByRole("button", { name: "Создать клиента", exact: true }).click();
  const clientResponse = await createdClient;
  expect(clientResponse.status()).toBe(201);
  const client = await clientResponse.json();
  expect(client.owner_id).toBe(2901);
  await page.getByRole("link", { name, exact: true }).click();
  await expect(page.getByRole("heading", { name, exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Добавить", exact: true }).click();
  await page.getByPlaceholder("ФИО контакта").fill("Анна Контрольная");
  await page.getByPlaceholder("Телефон", { exact: true }).fill("+375 (29) 111-22-33");
  await page.getByPlaceholder("Email", { exact: true }).fill("anna@example.test");
  let loseContactReply = true;
  const contactKeys: string[] = [];
  await page.route(`**/api/sales/clients/${client.id}/contacts`, async (route) => {
    if (route.request().method() !== 'POST') return route.continue();
    contactKeys.push(route.request().postDataJSON().request_key);
    if (!loseContactReply) return route.continue();
    loseContactReply = false;
    expect((await route.fetch()).status()).toBe(201);
    await route.abort('failed');
  });
  await page.getByRole("button", { name: "Сохранить контакт", exact: true }).click();
  await expect(page.getByRole("alert").filter({ hasText: "Не удалось сохранить контакт" })).toBeVisible();
  await page.getByRole("button", { name: "Сохранить контакт", exact: true }).click();
  await expect(page.getByRole("listitem").filter({ hasText: "Анна Контрольная" })).toBeVisible();
  expect(contactKeys).toHaveLength(2);
  expect(contactKeys[0]).toBe(contactKeys[1]);
  await page.reload();
  await expect(page.getByRole("listitem").filter({ hasText: "Анна Контрольная" })).toBeVisible();
  await page.getByRole("button", { name: "Новая сделка клиента", exact: true }).click();
  const dealForm = page.locator('form.shadow-pop');
  await dealForm.getByPlaceholder("CRM-2024-0200").fill(`OWN-${Date.now()}`);
  await dealForm.getByPlaceholder("Поставка ...").fill("Контрольный заказ");
  await expect(dealForm.getByPlaceholder("ООО ...")).toBeDisabled();
  const createdDeal = page.waitForResponse((r) => r.url().endsWith('/api/sales/deals') && r.request().method() === 'POST');
  await dealForm.getByRole("button", { name: "Создать", exact: true }).click();
  const dealResponse = await createdDeal;
  expect(dealResponse.status()).toBe(201);
  const deal = await dealResponse.json();
  expect(deal.crm_client_id).toBe(client.id);
  expect(deal.owner_id).toBe(2901);
  await page.getByRole("link", { name: new RegExp(deal.number) }).click();
  await expect(page).toHaveURL(new RegExp(`/crm/deals/${deal.id}$`));
  await expect(page.getByRole("listitem").filter({ hasText: "Анна Контрольная" })).toBeVisible();
  await page.getByPlaceholder("Что сделать…").fill("Согласовать доставку");
  await page.getByTitle("Срок (необязательно)").fill("2026-09-15T10:00");
  await page.getByRole("button", { name: "Задача", exact: true }).click();
  await expect(page.getByText("Согласовать доставку", { exact: true })).toBeVisible();
  const tasks = await (await page.request.get(`/api/sales/deals/${deal.id}/tasks`)).json();
  expect(tasks[0].assignee_id).toBe(2901);
  let loseHistoryReply = true;
  const historyKeys: string[] = [];
  await page.route(`**/api/sales/deals/${deal.id}/messages`, async (route) => {
    if (route.request().method() !== 'POST') return route.continue();
    historyKeys.push(route.request().postDataJSON().request_key);
    if (!loseHistoryReply) return route.continue();
    loseHistoryReply = false;
    expect((await route.fetch()).status()).toBe(201);
    await route.abort('failed');
  });
  await page.getByPlaceholder("Написать сообщение...").fill("Контрольная запись без отправки клиенту");
  await page.getByRole("button", { name: "Сохранить запись в историю", exact: true }).click();
  await expect(page.getByRole("alert").filter({ hasText: "Не удалось сохранить запись" })).toBeVisible();
  await page.getByRole("button", { name: "Сохранить запись в историю", exact: true }).click();
  await expect(page.getByText("Контрольная запись без отправки клиенту", { exact: true })).toBeVisible();
  expect(historyKeys).toHaveLength(2);
  expect(historyKeys[0]).toBe(historyKeys[1]);
  expect(await (await page.request.get(`/api/sales/deals/${deal.id}/messages`)).json()).toHaveLength(1);
  const selector = page.getByRole("combobox", { name: "Номенклатура (справочник из 1С через MDM)" });
  const sku = selector.locator('option').filter({ hasText: 'QA-ORDER' });
  await expect(sku).toHaveCount(1);
  await selector.selectOption((await sku.getAttribute('value'))!);
  await page.getByRole("spinbutton", { name: "Количество новой позиции", exact: true }).fill('2');
  await page.getByLabel("Цена за единицу новой позиции", { exact: true }).fill('125.50');
  const addedItem = page.waitForResponse((r) => r.url().endsWith(`/deals/${deal.id}/items`) && r.request().method() === 'POST');
  await page.getByRole("button", { name: "Добавить", exact: true }).first().click();
  expect((await addedItem).status()).toBe(201);
  await page.getByRole("checkbox", { name: "Под заказ — без резерва" }).check();
  const issued = page.waitForResponse((r) => r.url().endsWith(`/deals/${deal.id}/documents`) && r.request().method() === 'POST');
  await page.getByRole("button", { name: "Сформировать", exact: true }).click();
  expect((await issued).status()).toBe(201);
  const documents = await (await page.request.get(`/api/sales/deals/${deal.id}/documents`)).json();
  expect(documents).toHaveLength(1);
  expect(Number(documents[0].amount)).toBe(301.2);
  const documentId = documents[0].id;
  const original = await (await page.request.get(`/api/sales/documents/${documentId}/render`)).text();
  await page.reload();
  await expect(page.getByText("Согласовать доставку", { exact: true })).toBeVisible();
  await expect(page.getByRole("listitem").filter({ hasText: "Анна Контрольная" })).toBeVisible();
  expect(await (await page.request.get(`/api/sales/documents/${documentId}/render`)).text()).toBe(original);
  await page.screenshot({ path: test.info().outputPath('own-manager-cycle.png'), fullPage: true });
  await page.getByRole("button", { name: "Сформировать", exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: test.info().outputPath('own-manager-documents.png') });
  const originalPage = await context.newPage();
  await originalPage.goto(`/api/sales/documents/${documentId}/render`);
  await originalPage.screenshot({ path: test.info().outputPath('own-invoice-original.png'), fullPage: true });
  await originalPage.close();
  const contractReply = await page.request.post(`/api/sales/deals/${deal.id}/documents`, {
    data: {kind:'contract',request_key:`contract-${Date.now()}`},
  });
  expect(contractReply.status()).toBe(201);
  const contract = await contractReply.json();
  expect(contract.status).toBe('pending_approval');
  expect((await page.request.post(`/api/sales/documents/${contract.id}/decide`,{data:{approved:true}})).status()).toBe(403);
  const approver = await browser.newContext({baseURL,storageState:'e2e/.auth/state.json'});
  try {
    expect((await approver.request.post(`/api/sales/documents/${contract.id}/decide`,{data:{approved:true}})).status()).toBe(200);
  } finally { await approver.close(); }
  await page.reload();
  await page.getByRole('button',{name:'Email документов',exact:true}).click();
  const emailPanel = page.getByRole('region',{name:'Отправка документов по email',exact:true});
  await emailPanel.locator('label').filter({hasText:documents[0].number}).getByRole('checkbox').check();
  await emailPanel.locator('label').filter({hasText:contract.number}).getByRole('checkbox').check();
  await emailPanel.getByLabel('Кому (To)',{exact:true}).fill('control@example.invalid');
  await emailPanel.getByLabel('Тема',{exact:true}).fill('Контрольный пакет — без отправки');
  const prepared = page.waitForResponse(r => r.url().endsWith(`/deals/${deal.id}/emails/prepare`) && r.request().method()==='POST');
  await emailPanel.getByRole('button',{name:'Подготовить и проверить',exact:true}).click();
  const preparedReply = await prepared;
  expect(preparedReply.status()).toBe(201);
  const email = await preparedReply.json();
  expect(email.status).toBe('prepared');
  expect(email.attempt_count).toBe(0);
  expect(email.accepted_at).toBeNull();
  expect(email.attachments).toHaveLength(2);
  await expect(emailPanel.getByRole('button',{name:'Подтвердить отправку',exact:true})).toBeDisabled();
  const pdf = await page.request.get(`/api/sales/deals/${deal.id}/emails/${email.id}/attachments/0`);
  expect(pdf.status()).toBe(200);
  const bytes = await pdf.body();
  expect(bytes.subarray(0,5).toString()).toBe('%PDF-');
  await writeFile(test.info().outputPath('own-prepared-invoice.pdf'),bytes);
  await emailPanel.scrollIntoViewIfNeeded();
  await page.screenshot({path:test.info().outputPath('own-prepared-email.png')});
  await page.reload();
  const history = await (await page.request.get(`/api/sales/deals/${deal.id}/emails`)).json();
  expect(history).toHaveLength(1);
  expect(history[0].status).toBe('prepared');
  await page.goto(`/crm/clients/${client.id}`);
  const clientDocuments = page.getByRole("region", { name: "Документы клиента", exact: true });
  await expect(clientDocuments.getByRole("link", { name: `Оригинал ${documents[0].number}`, exact: true })).toBeVisible();
  const documentDealLinks = clientDocuments.getByRole("link", { name: `Сделка ${deal.number}`, exact: true });
  await expect(documentDealLinks).toHaveCount(2);
  for (const link of await documentDealLinks.all()) {
    await expect(link).toBeVisible();
    await expect(link).toHaveAttribute("href", `/crm/deals/${deal.id}`);
  }
  await clientDocuments.scrollIntoViewIfNeeded();
  await page.screenshot({ path: test.info().outputPath('own-client-documents.png') });
  expect((await page.request.get(`/api/sales/clients/${client.id}`, { headers: { 'X-User':'e2e_foreign', 'X-User-Roles':'director' } })).status()).toBe(200);
  for (const path of ['/api/service/tickets', '/api/system/mdm/counterparty']) expect((await page.request.get(path)).status()).toBe(403);
  const foreign = await browser.newContext({ baseURL });
  try {
    const other = await foreign.newPage();
    await other.goto('/login');
    await other.getByLabel('Сотрудник').selectOption('e2e_foreign');
    await other.getByRole('button', { name:'Войти', exact:true }).click();
    await expect(other).not.toHaveURL(/\/login/);
    for (const path of [`/api/sales/clients/${client.id}`, `/api/sales/clients/${client.id}/contacts`, `/api/sales/clients/${client.id}/documents`, `/api/sales/deals/${deal.id}`, `/api/sales/documents/${documentId}/render`, `/api/sales/deals/${deal.id}/emails/${email.id}/attachments/0`]) {
      expect((await other.request.get(path, { headers: { 'X-User':'e2e_owner', 'X-User-Roles':'director' } })).status()).toBe(404);
    }
    const hidden = await (await other.request.get(`/api/sales/clients?q=${encodeURIComponent(name)}`)).json();
    expect(hidden).toEqual({ rows:[], total:0 });
  } finally { await foreign.close(); }
});
