import { fetchRegisterDocument } from "./document-register-api";
import { fetchMoneyReview, validMoneyConfirmation, type MoneyConfirmation, type MoneyReview } from "./invoice-money-reconciliation-api";

export type Scope={org:number;deal:number;document:number};
export type Exact={organization_id:number;document_id:number;expected_version:number;expected_content_sha256:string};
export const sections=["wms_issue","wms_pick","logistics_shipment","accounting_issue","legacy_fulfillment"] as const;
export type Preview={exact_invoice:Exact;basis_digest:string;money:{digest:string;state:string;received:string;refunded:string};sections:Record<typeof sections[number],{facts:Record<string,unknown>;sha256:string}>;observed_blockers:string[];eligibility_issues?:{scope:string;code:string;message:string;detail:unknown}[];cancellation_authorized:false};
export type Basis={preview:Preview;money:MoneyReview};
export type ExternalSource={system:string;reference:string;history_from:string;history_through:string;confirmed_no_fulfillment:boolean};
export type ReviewBody={expected_version:number;expected_content_sha256:string;request_key:string;expected_basis_digest:string;money_reconciliation_id:number;evidence:string;external_sources:ExternalSource[];all_fulfillment_sources_identified:boolean};
export type CancelBody={expected_version:number;expected_content_sha256:string;request_key:string;fulfillment_review_id:string;expected_review_digest:string;evidence:string;acknowledge_invoice_invalidation:boolean};
export type ReviewReceipt={review_id:string;review_digest:string;organization_id:number;document_id:number;document_version:number;content_sha256:string;request_key:string;request_hash:string;basis_digest:string;money_reconciliation_id:number;actor:string;created_at:string;cancellation_authorized:false};
export type CancelReceipt={cancellation_id:string;digest:string;organization_id:number;document_id:number;document_version:number;content_sha256:string;request_key:string;request_hash:string;fulfillment_review_id:string;release_id:number;status:"cancelled";reserve_status:"released";customer_notification:"not_sent";actor:string;created_at:string};
export type MoneyReceipt={id:number;organization_id:number;document_id:number;source_key:string;request_hash:string;basis_digest:string;actor:string;created_at:string;history_from:string;history_through:string;evidence:string;source_references:string[]};
export type Attempt={schema:1;scope:Scope;phase:"money";body:MoneyConfirmation}|{schema:1;scope:Scope;phase:"review";body:ReviewBody}|{schema:1;scope:Scope;phase:"cancel";body:CancelBody};
export type Receipt=MoneyReceipt|ReviewReceipt|CancelReceipt;
export type Journal={schema:1;scope:Scope;pending:Attempt|null;review?:ReviewReceipt;history:{attempt:Attempt;outcome:"confirmed"|"rejected";receipt?:Receipt;reason?:string}[]};
export const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v);
const positive=(v:unknown):v is number=>typeof v==="number"&&Number.isSafeInteger(v)&&v>0;
export const hash=(v:unknown):v is string=>typeof v==="string"&&/^[a-f0-9]{64}$/.test(v);
const uuid=(v:unknown):v is string=>typeof v==="string"&&/^[a-f0-9]{8}-(?:[a-f0-9]{4}-){3}[a-f0-9]{12}$/.test(v);
const validDate=(v:unknown):v is string=>typeof v==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(`${v}T12:00:00Z`).toISOString().slice(0,10)===v;
export function canonical(v:unknown):string{if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(object(v))return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(",")}}`;return JSON.stringify(v);}
export async function digest(v:unknown){return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical(v))))).map(n=>n.toString(16).padStart(2,"0")).join("");}
export class CancellationError extends Error{constructor(message:string,readonly status?:number,readonly detail?:unknown){super(message);}}
function invalid():never{throw new CancellationError("Ответ не подтверждает выбранный счёт и сохранённый запрос. Результат неизвестен.");}
const sameScope=(a:Scope,b:Scope)=>a.org===b.org&&a.deal===b.deal&&a.document===b.document;
function path(s:Scope){if(![s.org,s.deal,s.document].every(positive))invalid();return`/api/sales/organizations/${s.org}/invoices/${s.document}`;}
function explain(detail:unknown):string{if(typeof detail==="string")return detail;if(object(detail)&&typeof detail.code==="string"){const ids=Array.isArray(detail.entry_ids)?detail.entry_ids.filter(positive):[];return`Требуется дополнительная проверка: ${detail.code}${ids.length?`. Проводки: ${ids.join(", ")}`:""}`;}return"Сервер не подтвердил операцию.";}
async function post(s:Scope,route:string,body:unknown){let r:Response;try{r=await fetch(`${path(s)}/${route}`,{method:"POST",cache:"no-store",headers:{"Content-Type":"application/json"},body:canonical(body)});}catch{throw new CancellationError("Связь прервана. Повторите сохранённый запрос с тем же ключом.");}let v:unknown;try{v=await r.json();}catch{invalid();}if(!r.ok){const detail=object(v)?v.detail:undefined;throw new CancellationError(r.status===403?"Недостаточно прав главного бухгалтера или доступа к источникам.":explain(detail),r.status,detail);}return v;}
export async function fetchBasis(s:Scope):Promise<Basis>{const doc=await fetchRegisterDocument(String(s.org),String(s.deal),s.document);if(doc.kind!=="invoice"||!hash(doc.content_sha256))invalid();const exact:Exact={organization_id:s.org,document_id:s.document,expected_version:doc.version,expected_content_sha256:doc.content_sha256};const [v,money]=await Promise.all([post(s,"cancellation/preview",{expected_version:doc.version,expected_content_sha256:doc.content_sha256}),fetchMoneyReview(String(s.org),String(s.document))]);if(!object(v)||canonical(v.exact_invoice)!==canonical(exact)||!hash(v.basis_digest)||!object(v.money)||!hash(v.money.digest)||!object(v.sections)||v.cancellation_authorized!==false||!Array.isArray(v.observed_blockers)||!v.observed_blockers.every(x=>typeof x==="string"))invalid();if(Object.keys(v.sections).sort().join()!==[...sections].sort().join())invalid();for(const name of sections){const item=v.sections[name];if(!object(item)||!object(item.facts)||!hash(item.sha256)||await digest(item.facts)!==item.sha256)invalid();}if(v.eligibility_issues!==undefined&&(!Array.isArray(v.eligibility_issues)||!v.eligibility_issues.every(i=>object(i)&&typeof i.scope==="string"&&typeof i.code==="string"&&typeof i.message==="string")))invalid();const without={...v};delete without.basis_digest;if(await digest(without)!==v.basis_digest)invalid();return{preview:v as Preview,money};}
export function currentMoney(b:Basis){return b.money.can_confirm_money_history&&b.money.basis_digest===b.preview.money.digest?b.money.records.find(r=>r.current&&r.basis_digest===b.preview.money.digest):undefined;}
export function currentReview(b:Basis,r:ReviewReceipt){return !b.preview.observed_blockers.length&&r.organization_id===b.preview.exact_invoice.organization_id&&r.document_id===b.preview.exact_invoice.document_id&&r.document_version===b.preview.exact_invoice.expected_version&&r.content_sha256===b.preview.exact_invoice.expected_content_sha256&&r.basis_digest===b.preview.basis_digest&&b.money.can_confirm_money_history&&b.money.basis_digest===b.preview.money.digest&&b.money.records.some(m=>m.id===r.money_reconciliation_id&&m.current&&m.basis_digest===b.preview.money.digest);}
export function moneyAttempt(s:Scope,b:Basis,form:Omit<MoneyConfirmation,"source_key"|"expected_basis_digest">):Attempt{const body={...form,source_key:crypto.randomUUID(),expected_basis_digest:b.money.basis_digest};if(!validMoneyConfirmation(body,b.money))throw new CancellationError("Проверьте период, основания и подтверждение всех денежных источников.");return{schema:1,scope:s,phase:"money",body};}
export function reviewAttempt(s:Scope,b:Basis,evidence:string,external_sources:ExternalSource[],checked:boolean):Attempt{const record=currentMoney(b),bounds=b.preview.sections.legacy_fulfillment.facts;if(!record||b.preview.observed_blockers.length)throw new CancellationError("Нужны актуальная денежная сверка и отсутствие блокировок.");if(!checked||!evidence.trim()||evidence.trim().length>2000||!external_sources.length||external_sources.length>100)throw new CancellationError("Подтвердите полноту именованных источников исполнения.");const names=new Set<string>();for(const x of external_sources){const k=canonical([x.system.trim(),x.reference.trim()]);if(!x.system.trim()||x.system.length>200||!x.reference.trim()||x.reference.length>1000||!x.confirmed_no_fulfillment||!validDate(x.history_from)||!validDate(x.history_through)||x.history_from>x.history_through||x.history_from>String(bounds.required_history_from)||x.history_through<String(bounds.required_history_through)||x.history_through>b.money.review_date||names.has(k))throw new CancellationError("У каждого источника нужны точное основание, полный период и подтверждение отсутствия исполнения.");names.add(k);}return{schema:1,scope:s,phase:"review",body:{expected_version:b.preview.exact_invoice.expected_version,expected_content_sha256:b.preview.exact_invoice.expected_content_sha256,request_key:crypto.randomUUID(),expected_basis_digest:b.preview.basis_digest,money_reconciliation_id:record.id,evidence:evidence.trim(),external_sources:external_sources.map(x=>({...x,system:x.system.trim(),reference:x.reference.trim()})),all_fulfillment_sources_identified:true}};}
export function cancelAttempt(s:Scope,b:Basis,r:ReviewReceipt,evidence:string,checked:boolean):Attempt{if(!currentReview(b,r))throw new CancellationError("Сверка исполнения устарела. Обновите основания и начните новую сверку.");if(!checked||!evidence.trim()||evidence.trim().length>1000)throw new CancellationError("Подтвердите утрату силы счёта и укажите причину.");return{schema:1,scope:s,phase:"cancel",body:{expected_version:r.document_version,expected_content_sha256:r.content_sha256,request_key:crypto.randomUUID(),fulfillment_review_id:r.review_id,expected_review_digest:r.review_digest,evidence:evidence.trim(),acknowledge_invoice_invalidation:true}};}
export async function sendAttempt(a:Attempt):Promise<Receipt>{const v=await post(a.scope,a.phase==="money"?"money-reconciliation":a.phase==="review"?"fulfillment-review":"cancel",a.body);if(!object(v)||v.organization_id!==a.scope.org||v.document_id!==a.scope.document||typeof v.actor!=="string"||!v.actor||typeof v.created_at!=="string"||!Number.isFinite(Date.parse(v.created_at))||v.request_hash!==await digest(a.body))invalid();if(a.phase==="money"){if(v.source_key!==a.body.source_key||!positive(v.id)||v.basis_digest!==a.body.expected_basis_digest||v.history_from!==a.body.history_from||v.history_through!==a.body.history_through||v.evidence!==a.body.evidence||canonical(v.source_references)!==canonical(a.body.source_references))invalid();}else{if(v.request_key!==a.body.request_key||v.document_version!==a.body.expected_version||v.content_sha256!==a.body.expected_content_sha256)invalid();if(a.phase==="review"){if(!uuid(v.review_id)||!hash(v.review_digest)||v.basis_digest!==a.body.expected_basis_digest||v.money_reconciliation_id!==a.body.money_reconciliation_id||v.cancellation_authorized!==false)invalid();}else if(!uuid(v.cancellation_id)||!hash(v.digest)||!positive(v.release_id)||v.fulfillment_review_id!==a.body.fulfillment_review_id||v.status!=="cancelled"||v.reserve_status!=="released"||v.customer_notification!=="not_sent")invalid();}return v as Receipt;}
const rejected=new Set(["Money facts or history coverage require a new reconciliation","Current invoice facts do not support a no-shipment review","External fulfillment history coverage requires a new review","A current confirmed complete money reconciliation is required","A current confirmed fulfillment review is required","Unprocessed accounting sources require reconciliation"]);
export function definiteRejection(e:unknown){return e instanceof CancellationError&&e.status===409&&(typeof e.detail==="string"&&rejected.has(e.detail)||object(e.detail)&&e.detail.code==="accounting_fulfillment_classification_required");}
export const journalKey=(s:Scope)=>`invoice-cancellation:v1:${s.org}:${s.deal}:${s.document}`;
function validAttempt(v:unknown,s:Scope):v is Attempt{if(!object(v)||v.schema!==1||!object(v.scope)||!sameScope(v.scope as Scope,s)||!object(v.body)||!["money","review","cancel"].includes(String(v.phase)))return false;const b=v.body;return uuid(v.phase==="money"?b.source_key:b.request_key)&&(v.phase==="money"?hash(b.expected_basis_digest):positive(b.expected_version)&&hash(b.expected_content_sha256));}
export function readJournal(s:Scope):Journal{const raw=sessionStorage.getItem(journalKey(s));if(!raw)return{schema:1,scope:s,pending:null,history:[]};const v:unknown=JSON.parse(raw);if(!object(v)||v.schema!==1||!object(v.scope)||!sameScope(v.scope as Scope,s)||!Array.isArray(v.history)||(v.pending!==null&&!validAttempt(v.pending,s)))throw new CancellationError("Журнал восстановления повреждён. Новые запросы заблокированы.");return v as Journal;}
function store(j:Journal){const raw=canonical(j);sessionStorage.setItem(journalKey(j.scope),raw);if(sessionStorage.getItem(journalKey(j.scope))!==raw)throw new CancellationError("Не удалось сохранить запрос. Отправка остановлена.");}
export function persist(a:Attempt){const j=readJournal(a.scope);if(j.pending&&canonical(j.pending)!==canonical(a))throw new CancellationError("Для счёта уже сохранён другой запрос. Сначала проверьте его результат.");store({...j,pending:a});}
export function settle(a:Attempt,receipt?:Receipt,reason?:string){const j=readJournal(a.scope);if(canonical(j.pending)!==canonical(a))return false;const next={...j,pending:null,history:[...j.history,{attempt:a,outcome:receipt?"confirmed" as const:"rejected" as const,...(receipt?{receipt}:{reason})}],...(receipt&&a.phase==="review"?{review:receipt as ReviewReceipt}:{})};store(next);return true;}
export function forgetReview(s:Scope){const j=readJournal(s);if(j.pending)throw new CancellationError("Сначала проверьте сохранённый запрос.");const next={...j};delete next.review;store(next);}
