import { webcrypto } from "node:crypto";
import { afterEach,beforeEach,expect,it,vi } from "vitest";
import { cancelAttempt,CancellationError,canonical,currentMoney,currentReview,definiteRejection,digest,fetchBasis,journalKey,moneyAttempt,persist,readJournal,reviewAttempt,sendAttempt,settle,type Attempt,type Basis,type ReviewReceipt } from "./invoice-cancellation-api";
const h="a".repeat(64),key="11111111-1111-4111-8111-111111111111",s={org:7,deal:3,document:11};
function basis():Basis{return{preview:{exact_invoice:{organization_id:7,document_id:11,expected_version:2,expected_content_sha256:h},basis_digest:h,money:{digest:h,state:"no_receipts",received:"0.00",refunded:"0.00"},sections:{wms_issue:{facts:{observed_state:"no_shipment"},sha256:h},wms_pick:{facts:{picks:[]},sha256:h},logistics_shipment:{facts:{shipments:[],rfqs:[]},sha256:h},accounting_issue:{facts:{facts:{entries:[]}},sha256:h},legacy_fulfillment:{facts:{required_history_from:"2026-01-01",required_history_through:"2026-09-10"},sha256:h}},observed_blockers:[],eligibility_issues:[],cancellation_authorized:false},money:{organization_id:7,document_id:11,review_date:"2026-09-10",basis_digest:h,money_state:"no_receipts",blockers:[],required_history_from:"2026-01-01",required_history_through:"2026-09-10",can_confirm_money_history:true,fulfillment_required:true,records:[{id:4,current:true,organization_id:7,document_id:11,basis_digest:h,history_from:"2026-01-01",history_through:"2026-09-10",actor:"chief",created_at:"2026-09-10T00:00:00Z",evidence:"checked",source_references:["bank"]}]}};}
const review:ReviewReceipt={review_id:key,review_digest:h,organization_id:7,document_id:11,document_version:2,content_sha256:h,request_key:key,request_hash:h,basis_digest:h,money_reconciliation_id:4,actor:"chief",created_at:"2026-09-10T00:00:00Z",cancellation_authorized:false};
const makeMoney=()=>moneyAttempt(s,basis(),{history_from:"2026-01-01",history_through:"2026-09-10",evidence:"Банк проверен",source_references:["bank:1"],all_money_sources_checked:true});
const makeReview=()=>reviewAttempt(s,basis(),"Полная сверка",[{system:"Перевозчик",reference:"Ответ 12",history_from:"2026-01-01",history_through:"2026-09-10",confirmed_no_fulfillment:true}],true);
const makeCancel=()=>cancelAttempt(s,basis(),review,"Ошибочный счёт",true);
async function reply(a:Attempt){const common={organization_id:7,document_id:11,actor:"chief",created_at:"2026-09-10T00:00:00Z",request_hash:await digest(a.body)};if(a.phase==="money")return{...common,id:4,source_key:a.body.source_key,basis_digest:h,history_from:a.body.history_from,history_through:a.body.history_through,evidence:a.body.evidence,source_references:a.body.source_references};if(a.phase==="review")return{...review,...common,request_key:a.body.request_key};return{...common,cancellation_id:key,digest:h,request_key:a.body.request_key,document_version:2,content_sha256:h,fulfillment_review_id:key,release_id:3,status:"cancelled",reserve_status:"released",customer_notification:"not_sent"};}
const ok=(v:unknown,status=200)=>({ok:status<400,status,json:async()=>v});
beforeEach(()=>{vi.stubGlobal("crypto",webcrypto);sessionStorage.clear();});afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals();});
it("matches Python canonical UTF-8 SHA and excludes no fields",async()=>{expect(canonical({b:"я",a:1})).toBe('{"a":1,"b":"я"}');expect(await digest({a:1})).toBe("015abd7f5cc57a2dd94b7590f04ad8084273905ee33ec5cebeae62276a97f862");});
it.each([makeMoney,makeReview,makeCancel])("persists exact phase and validates matched receipt",async make=>{const a=make();persist(a);const saved=readJournal(s).pending!;expect(saved).toEqual(a);const r=await reply(a);const f=vi.fn().mockResolvedValue(ok(r));vi.stubGlobal("fetch",f);const got=await sendAttempt(saved);expect(f.mock.calls[0][1].body).toBe(canonical(a.body));expect(settle(a,got)).toBe(true);expect(readJournal(s).pending).toBeNull();expect(readJournal(s).history).toHaveLength(1);});
it.each(["org","key","hash","version","notification"])("rejects wrong cancel receipt %s",async field=>{const a=makeCancel(),r:Record<string,unknown>=await reply(a);if(field==="org")r.organization_id=8;if(field==="key")r.request_key=crypto.randomUUID();if(field==="hash")r.request_hash=h;if(field==="version")r.document_version=3;if(field==="notification")r.customer_notification="sent";vi.stubGlobal("fetch",vi.fn().mockResolvedValue(ok(r)));await expect(sendAttempt(a)).rejects.toThrow();});
it.each([makeMoney,makeReview])("rejects wrong source identity for earlier phase",async make=>{const a=make(),r:Record<string,unknown>=await reply(a);r[a.phase==="money"?"source_key":"request_key"]=crypto.randomUUID();vi.stubGlobal("fetch",vi.fn().mockResolvedValue(ok(r)));await expect(sendAttempt(a)).rejects.toThrow();});
it("does not replace or clear a different newer pending A",()=>{const old=makeMoney(),newer=makeMoney();persist(old);settle(old,undefined,"definite failure");persist(newer);expect(settle(old,undefined,"late callback")).toBe(false);expect(()=>persist(old)).toThrow();expect(readJournal(s).pending).toEqual(newer);expect(readJournal({...s,document:12}).pending).toBeNull();});
it("storage failure blocks persistence",()=>{vi.stubGlobal("sessionStorage",{getItem:()=>null,setItem:()=>{throw new Error("quota");}});expect(()=>persist(makeMoney())).toThrow("quota");});
it("unknown 409 and current-auth failures do not authorize restart",()=>{for(const status of [401,403,404,409,500])expect(definiteRejection(new CancellationError("unknown",status,"Key conflict"))).toBe(false);expect(definiteRejection(new CancellationError("stale",409,"Money facts or history coverage require a new reconciliation"))).toBe(true);});
it("requires explicit money/coverage/invalidation and current records",()=>{const b=basis();b.money.records[0].current=false;expect(currentMoney(b)).toBeUndefined();expect(currentReview(b,review)).toBe(false);expect(()=>cancelAttempt(s,b,review,"x",true)).toThrow();expect(()=>cancelAttempt(s,basis(),review,"x",false)).toThrow();expect(()=>reviewAttempt(s,basis(),"x",[],true)).toThrow();expect(()=>moneyAttempt(s,basis(),{history_from:"2026-01-01",history_through:"2026-09-10",evidence:"x",source_references:["x"],all_money_sources_checked:false})).toThrow();});
it("accepts matching current money record even when another current record appears first",()=>{const b=basis();b.money.records.unshift({...b.money.records[0],id:5});expect(currentReview(b,review)).toBe(true);});
it("detects corrupt storage and does not fabricate a pending request",()=>{sessionStorage.setItem(journalKey(s),'{"schema":1}');expect(()=>readJournal(s)).toThrow();});
it("hashes full preview including new eligibility fields and rejects tampering",async()=>{const b=basis();for(const item of Object.values(b.preview.sections))item.sha256=await digest(item.facts);const body={...b.preview};delete (body as Partial<typeof body>).basis_digest;b.preview.basis_digest=await digest(body);const doc={id:11,deal_id:3,organization_id:7,kind:"invoice",number:"I",version:2,status:"posted",amount:"1.00",currency:"BYN",created_at:null,issued_at:null,valid_until:null,reserve_status:"reserved",onec_ref:null,original_state:"issued",content_sha256:h,replacement_reason:null,supersedes_id:null,superseded_by_id:null,original_available:true,preview_available:false};const f=vi.fn().mockImplementation((url:string)=>Promise.resolve(ok(url.endsWith("cancellation/preview")?b.preview:url.endsWith("money-reconciliation")?b.money:doc)));vi.stubGlobal("fetch",f);expect((await fetchBasis(s)).preview.basis_digest).toBe(b.preview.basis_digest);b.preview.eligibility_issues=[{scope:"accounting_issue",code:"blocked",message:"blocked",detail:"new"}];await expect(fetchBasis(s)).rejects.toThrow();});
